### ISSUE TITLE
Double logging with dd-trace in Django under Gunicorn

### ISSUE THREAD

**Issue by Jastrzebowski** [DataDog/dd-trace-py#1012]
I keep getting double logs while running a Django application with JSON logs (using python-json-logger) running using Gunicorn. For each message, I'm getting an unformatted next to a JSONified one:

```
web_1         | {"severity": "DEBUG", "request": null, "levelname": "DEBUG", "asctime": "2019-08-05 18:54:48,090", "message": "test logs", "name": "dashboard.models", "funcName": "<module>", "pathname": "/code/dashboard/models.py", "lineno": 26}
web_1         | 2019-08-05 18:54:48,090 DEBUG [dashboard.models] [models.py:26] - test logs
```

Only happens when I run the application using dd-trace, Config file is used to format gunicorn logs also as JSON:

```
ddtrace-run gunicorn --bind 0.0.0.0:8000 --config app/gunicorn.conf.py app.wsgi
```

The problem occurs both locally running a container using docker-compose and remotely running using Kubernetes. 

* ddtrace: 0.27.1
* Python: 3.6
* Django: 2.1.5
* Gunicorn: 19.9.0

Having the same issue in another application running Django 1.7 and python 2.7

As I'm also using config file for Gunicorn maybe has something to do with:
https://github.com/DataDog/dd-trace-py/issues/786

**Comment by Jastrzebowski** [comment]
I've set up a quick example showing double logging: https://github.com/Jastrzebowski/ddlog

**Comment by adriandavidsmith** [comment]
@Jastrzebowski Any update or comms on this issue from the DD team?

**Comment by peter-bertuglia** [comment]
In case anyone is still encountering this issue, or encounters it, the problem is having multiple `StreamHandler`s set on the root logger. `dd-trace` calls `logging.basicConfig(format=DD_LOG_FORMAT)` during it's bootstrapping process, which creates a `StreamHandler` on the root logger. Then, as part of setting up `python-json-logger`, you create another `StreamHandler` and set the JSON formatter on it. There are 2 options to fix this:

For the first option, prior to adding the `StreamHandler` created for `python-json-logger`, you can just remove any other `StreamHandler`s set on the root logger
```
logger = logging.getLogger()
logger.handlers = [h for h in logger.handlers if not isinstance(h, logging.StreamHandler)]
```
The second option is to just find the `StreamHandler` instance in the `logger.handlers` list and call `setFormatter` on it, passing the JSON formatter.

**Comment by Kyle-Verhoog** [comment]
Hey all, we added a flag `DD_CALL_BASIC_CONFIG` to disable the calling of `basicConfig` by `ddtrace`:  https://ddtrace.readthedocs.io/en/stable/configuration.html which should help mitigate this issue. 

We do have plans to change this behaviour in the long term (unfortunately can't in the short term for compatibility) see #2713 for more information.
