### ISSUE TITLE
LLM observability data is being sent even though DD_LLMOBS_ENABLED is set to "0"

### ISSUE THREAD

**Issue by Gekko0114** [DataDog/dd-trace-py#10859]
### Summary of problem
I was using `with LLMObs.llm():` in a function to track LLM observability, intending to control whether the data is sent based on the development environment.
I configured this behavior using the `DD_LLMOBS_ENABLED` setting.
However, despite setting `DD_LLMOBS_ENABLED` to "0", LLM obs data was sent when using `with LLMObs.llm():)`.
Is this the expected behavior or a bug?

### Which version of dd-trace-py are you using?
2.11.2

### Which libraries and their versions are you using?
FastAPI

<details>
  <summary>`pip freeze`</summary>
  
</details>

### How can we reproduce your problem?
I set `DD_LLMOBS_ENABLED` is set to "0", and used with LLMObs.llm():

### What is the result that you get?
Data is sent.

### What is the result that you expected?
Data is not sent.

**Comment by Gekko0114** [comment]
I have created a PR which might reproduce my issue.

**Comment by lievan** [comment]
Hi @Gekko0114, if I understand correctly, this is a case where you 1) enable LLM Observability but then 2) want to disable data being sent in certain circumstances?

If `DD_LLMOBS_ENABLED` is set to 0, LLM Observability will not be enabled even if you call `enable`. However, if you:
1. Call `LLMObs.enable()` while `DD_LLMOBS_ENABLED` is unset or `DD_LLMOBS_ENABLED=1`
2. Then set `DD_LLMOBS_ENABLE=0`

You're right that LLM Observability data will still be sent after `2`, since we do not support disabling LLM Obs on the fly. 

Also, I want to clarify that `LLMObs` is enabled by default—In the PR you linked, you use the `LLMObs` test fixture which calls `llmobs.enable()`

**Comment by Gekko0114** [comment]
Hi @lievan,
This is my situation:

1. In the production environment variables, DD_LLMOBS_ENABLED=0 is set.
2. In the code, `with LLMObs.llm()` is called.
3. Then LLMOBS telemetry is being sent.

Is this behavior as expected? My PR might not be correctly reproducing this situation.

**Comment by lievan** [comment]
Hey @Gekko0114, that is not expected behavior—LLM Observability data should not be sent if `DD_LLMOBS_ENABLED=0` is set and LLMObs is not already enabled. 

Unfortunately the PR does not correctly reproduce this behavior because `LLMObs.enable()` is called before `DD_LLMOBS_ENABLED=0` is set. 

Do you mind sending a script to reproduce your issue? The expected behavior is if `DD_LLMOBS_ENABLED=0` and you call `LLMObs.llm`, you should see this log:
`"Span started while LLMObs is disabled." " Spans will not be sent to LLM Observability."`

**Comment by Gekko0114** [comment]
> Do you mind sending a script to reproduce your issue? 

My script is very simple.
On my ECS cluster, I set DD_LLMOBS_ENABLED = 0, and then called `with LLMObs.llm()`.

Then I got following logs.
```
2024-10-05 13:55:07,051 DEBUG ddtrace._trace.processor :initialized processor SpanAggregator(True, 300, [<ddtrace.internal.peer_service.processor.PeerServiceProcessor object at 0x7f482439e810>, <ddtrace.internal.schema.processor.BaseServiceProcessor object at 0x7f482439e4e0>, <ddtrace._trace.processor.TraceSamplingProcessor object at 0x7f482439e5a0>, <ddtrace._trace.processor.TraceTagsProcessor object at 0x7f482439e630>, <ddtrace.llmobs._trace_processor.LLMObsTraceProcessor object at 0x7f4858219790>], AgentWriter(status=<ServiceStatus.STOPPED: 'stopped'>, intake_url='http://localhost:8126', dogstatsd=<ddtrace.vendor.dogstatsd.base.DogStatsd object at 0x7f482439e750>))

2024-10-05 13:55:07,051 DEBUG ddtrace.llmobs._writer :started 'LLMObsSpanWriter' to 'http://localhost:8126'

2024-10-05 13:57:43,166 WARNING ddtrace.llmobs._llmobs :Span started while LLMObs is disabled. Spans will not be sent to LLM Observability.

2024-10-05 13:57:45,182 DEBUG ddtrace.llmobs._writer :encode 1 LLMObs span events to be sent

Sending request: POST evp_proxy/v2/api/v2/llmobs {'X-Datadog-EVP-Subdomain': 'llmobs-intake', 'Content-Type': 'application/json'}

2024-10-05 13:57:45,182 DEBUG ddtrace.internal.writer.writer :Sending request: POST evp_proxy/v2/api/v2/llmobs {'X-Datadog-EVP-Subdomain': 'llmobs-intake', 'Content-Type': 'application/json'}

sent 659B in 0.63583s to http://localhost:8126/evp_proxy/v2/api/v2/llmobs

```

I used the newest dd-trace-py version. So this issue hasn't been fixed yet.

**Comment by Gekko0114** [comment]
Also I reproduced my bug. Tracer is called even though LLMObs is not enabled.
https://github.com/DataDog/dd-trace-py/pull/10860

**Comment by Gekko0114** [comment]
Hi @lievan 
Could you take a look?

**Comment by lievan** [comment]
Hey @Gekko0114, seeing both 
`2024-10-05 13:57:43,166 WARNING ddtrace.llmobs._llmobs :Span started while LLMObs is disabled. Spans will not be sent to LLM Observability.
`

and

`Sending request: POST evp_proxy/v2/api/v2/llmobs ...`
`2024-10-05 13:55:07,051 DEBUG ddtrace.llmobs._writer :started 'LLMObsSpanWriter' to 'http://localhost:8126'`

Is not expected - we'll take a look at what might be happening and get back to you!

**Comment by lievan** [comment]
Hey @Gekko0114 - by any chance, are you using `LLMObs.llm` within a forked process?

**Comment by Gekko0114** [comment]
Yes I am using it within async.

**Comment by Kyle-Verhoog** [comment]
Hey @Gekko0114! Could you try out the fix proposed in https://github.com/DataDog/dd-trace-py/pull/11026? There was indeed an issue when forking.

**Comment by Gekko0114** [comment]
Hi @Kyle-Verhoog,

Thanks so much! I will try it when I have time. BTW, you can merge that PR if it is OK. 
I am not sure when I can check it.
