### ISSUE TITLE
How do I set the the service_name globally

### ISSUE THREAD

**Issue by raags** [DataDog/dd-trace-py#1088]
There was a call called `set_service_info`, but its deprecated: https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/tracer.py#L508

I can set it on `trace()`, but is there a way to set this globally?

**Comment by majorgreys** [comment]
If you are using `ddtrace-run`, you can override the default service name with the `DATADOG_SERVICE_NAME` environment variable:

http://pypi.datadoghq.com/trace/docs/advanced_usage.html#ddtracerun

Otherwise, you can do so when you start a root span for the program with the `service` keyword argument for `Tracer.trace()`, `Tracer.start_span()`, or the decorator `ddtrace.trace.wrap()`.
