### ISSUE TITLE
Getting warning message from span_pointers.dynamodb

### ISSUE THREAD

**Issue by anna20160606** [DataDog/dd-trace-py#11320]
Get warning message, but looks like AWS DB update went through. What kind of error does this message indicates? Assume this exception will not break the existing function?

WARNING [ddtrace._trace.utils_botocore.span_pointers.dynamodb] [dynamodb.py:181] [dd.service=<SERVICE_NAME>.env=prod dd.version=<VERSION> dd.span_id=<SPAN_ID>] - failed to generate DynamoDB.UpdateItem span pointer: primary key value object must have exactly one field: 12, 2 additional messages skipped

Maybe related to this change? https://github.com/DataDog/dd-trace-py/commit/b98138ca250e1497182926c67e1bc1c367c12c2f

**Comment by apiarian-datadog** [comment]
Hello! Thanks for letting us know about this. The span pointer code fails safe, so while these spans won't have span pointers associated with them, the rest of the code should work just fine.

We wrote the logic based on the documentation available to us. Perhaps the underlying boto3 api handling is more flexible than their docs had suggested?

Could you share more about the schema of the table (the primary key in particular) and an example of the boto3 api call you are making? That should help us adjust our parsing logic accordingly.

**Comment by apiarian-datadog** [comment]
Ah, interesting. Our code currently assumes that the dynamo api is being called with value objects, not values. i.e. `{"PK": {"S": "something"}, ... }` rather than `{"PK": "something", ...}`. I couldn't get the latter working with some of the lower level APIs, but perhaps the `Table` version of `put_item` does more interesting argument processing. I'll update our code to handle this form as well.

**Comment by robotmlg** [comment]
Hi, I just want to report that I'm also experiencing this issue on `Table.update_item` and `Table.delete_item`.  I see later commits from you for methods (and more), so I just wanted to make sure they're also on your radar for a fix.  

the exact code:
```
table.update_item(
            Key={"id": id},
            ExpressionAttributeNames={"#k": key},
            ExpressionAttributeValues={':inc': amount, ':start': 0, ':id': id},
            ConditionExpression='id = :id',
            UpdateExpression='SET #k = if_not_exists(#k, :start) + :inc'
        )
# log: failed to generate DynamoDB.UpdateItem span pointer: primary key value object must have exactly one field: 8, 1 additional messages skipped

table.delete_item(Key={"id": id, "type": type})
# log: failed to generate DynamoDB.DeleteItem span pointer: primary key value object must have exactly one field: 16
```

Let me know if you need more details from me.

**Comment by apiarian-datadog** [comment]
Hi folks, thanks for the feedback!

I think we've got a fix that should cover all of the documented `Table` resource methods (I've tested it with `table.put_item`, `table.update_item`, `table.delete_item`, as well as `table.batch_writer`). We also have a patch in progress to make the logging less noisy.

These fixes will probably be out in the next release and we'll backport them to 2.16 as a patch as well.

**Comment by apiarian-datadog** [comment]
The fix for this issue has been released in [v2.16.4](https://github.com/DataDog/dd-trace-py/releases/tag/v2.16.4). Please let us know if you see any other issues!

**Comment by shun-tak** [comment]
First of all, thank you for addressing the previous issue where the error:

```
failed to generate DynamoDB.PutItem span pointer: 'my-table-1'
```

was occurring.


After applying the patch in version 2.16.4, the original issue seems to be resolved. However, a new error has emerged during the same operation:

```
span pointers: failed to extract DynamoDB.PutItem span pointer: table 'my-table-1' not found in primary key names
```

Despite providing valid input for the DynamoDB PutItem operation, the tracer fails.

Once again, thank you for addressing the previous issue. I hope this additional context helps in investigating and resolving this new error. Please let me know if there is anything else I can provide to assist.

**Comment by apiarian-datadog** [comment]
Hi @shun-tak ! That's a separate issue. Due to the limitations of the DynamoDB API, we can't know which of the fields of a `PutItem` request are actually the primary key fields. In such cases, we need the [ddtrace.config.botocore dynamodb_primary_key_names_for_tables](https://ddtrace.readthedocs.io/en/stable/integrations.html#id28) configuration parameter to be set.

As with the other warnings, the actual AWS API call shouldn't be disrupted, the tracer just won't be able to create a span pointer for the associated span.

**Comment by shun-tak** [comment]
Thanks for the quick response! Setting the `ddtrace.config.botocore["dynamodb_primary_key_names_for_tables"]` parameter worked perfectly, and my error is now resolved. Appreciate the help!

**Comment by andrii-korotkov-verkada** [comment]
Is it possible to silence the warning somehow? We started seeing a spam of messages across a lot of services after the upgrade.

**Comment by apiarian-datadog** [comment]
> Is it possible to silence the warning somehow? We started seeing a spam of messages across a lot of services after the upgrade.

Hi @andrii-korotkov-verkada ,

Thanks for letting us know. https://github.com/DataDog/dd-trace-py/pull/12763 will change that message to a debug level instead of a warning.

In the meantime you can try changing the `DD_TRACE_LOGGING_RATE` https://github.com/DataDog/dd-trace-py/blob/main/ddtrace/internal/logger.py#L29 to decrease how often messages actually get generated.

Al
