### ISSUE TITLE
Add configuration option for partial flush

### ISSUE THREAD

**Issue by berkowitzi** [DataDog/dd-trace-py#1159]
#668 implemented support for partial flushes, yet did not expose a top-level configuration flag to enable this support. As such, configuration is only currently possible via environment variable. Add those config options here, backing both `_partial_flush_enabled` (default `False`), and `_partial_flush_min_spans` (default `500`).

**Comment by brettlangdon** [comment]
hey @berkowitzi thanks for opening this issue. Do you mind me asking why you need to enable partial flushing?

I am just curious about your current trace structure that would require partial flushing.

**Comment by berkowitzi** [comment]
Hi @brettlangdon ,
We're using `ddtrace` to send traces from a python/postgres monolith to LightStep. We've found that for some of our longer async/batch operations, the data just isn't making it out of `ddtrace` (we actually haven't been seeing any errors logged either), but that enabling partial flushes had solved the issue.
For reference, we're looking at traces with ~1000 spans (still working on getting a better idea of the overall serialized size).
I was going to take a stab at implementing this, but then found (maybe as alluded to on the original issue) that there isn't an incredibly clear path to doing so since the config system is a little disjointed. I still may take it on if I find some extra time in the next few days/weeks, though.
Do you have any concerns about the stability of this feature? Is there another change that would potentially obviate it?
Thanks!
Isaac

**Comment by brettlangdon** [comment]
Hey @berkowitzi 

What do you mean by:

> We're using ddtrace to send traces from a python/postgres monolith to LightStep

Curious to hear about how you have the tracer configured. (this is the first time I've heard anyone use our tracer like this)

**Comment by berkowitzi** [comment]
Hi @brettlangdon - my understanding was that in connectin with this announcement around `ddtrace` and OpenTelemetry https://www.datadoghq.com/blog/opentelemetry-instrumentation/, LightStep updates their infrastructure to be able to consume tracing data coming off of the `ddtrace` tracers. We chose to take advantage of this and use `ddtrace-py` over the LightStep tracer because it gave us more auto-instrumentation out of the box. Configuration is relatively simple, we just set some global tags and point at our LightStep satellites instead of a datadog agent.

**Comment by brettlangdon** [comment]
Ah, yeah. So `dd-trace-py` was actually forked and being used as the basis for OpenTelemetry auto-instrumentation library. This library still only supports submitting traces to the Datadog trace agent and platform. The OpenTelemetry fork of this project has not yet been released.

**Comment by berkowitzi** [comment]
@brettlangdon my understanding is that LightStep added support for the ddtrace wire format a couple of months ago so this library does actually support sending tracing data to their infrastructure. We’ve been using it in production without issue (present issue of minimal dropped traces not withstanding) for that time.

**Comment by brettlangdon** [comment]
Interesting, this is news to me, thanks for sharing. This is all helpful context.

Back to the problem at hand.

I actually wouldn't expect traces with 1k spans to be too much of a problem unless you are generating a ton of them. Is there a specific problem you are seeing, is there a timeout issues, or do they get rejected by the agent, etc?

Some other hopefully helpful context. The reason we have tried to keep partial flushing configuration "private" is because it has some known issues with our system; mainly around how metrics are properly generated for traces, and how traces are normalized.

Are you enabling via `_partial_flush_enabled=True` and everything is working properly? Just looking for a non-private way to enable?

**Comment by samschlegel** [comment]
@brettlangdon For some context, we've been running into issues with MemoryErrors that appear to stem from long-running traces, as enabling partial flushes seems to stop them. This is mostly on celery workers that are running things with potentially 10s of thousands of spans, but we're also seeing it on some gunicorn workers. The gunicorn one is a bit more concerning as we shouldn't have requests that long, so I think that one might actually be due to a bug where something we're doing is causing some context to leak out and be shared between all requests, like in some gevent Pool or worker kinda thing.

I'd love to have a way to configure this in in Python instead of environment variables, but I think I'd also want this config to be moved to the tracer, so that we could easily update it at runtime across existing contexts.

**Comment by brettlangdon** [comment]
hey @samschlegel 

> The gunicorn one is a bit more concerning as we shouldn't have requests that long, so I think that one might actually be due to a bug where something we're doing is causing some context to leak out and be shared between all requests, like in some gevent Pool or worker kinda thing.

Can you tell me a little about your gunicorn setup? Any config/cli options you can share, etc. If we are not able to patch Gevent for context propagation then requests will get lumped together.

If you'd rather not share those details here, please feel free to reach out at support@datadoghq.com and reference this GitHub issue.


> so that we could easily update it at runtime across existing contexts.

Can you explain to me your use-case for configuring it at runtime? It sounds like you want to dynamically control whether it is enabled or not depending on memory usage (or... something like that?).


In general my largest concern is still around how partial flushing interacts with our system, it can cause undesired side effects in how metrics are computed. Not saying this should be a hard blocker for us exposing an option, just want to be forward with where my apprehensions are in making it easy to configure.

**Comment by samschlegel** [comment]
> Can you tell me a little about your gunicorn setup? Any config/cli options you can share, etc. If we are not able to patch Gevent for context propagation then requests will get lumped together.

I'm not sure if it's anything particularly related to our gunicorn setup, as that's pretty straightforward. If I recall correctly I think one thing we tracked down was related to every task in a gevent.Pool being tied to the first trace that created it, but iirc this was also pre-gevent.Pool support. The thing that makes it hard to rule out though is that the only way we found this was by looking for spans that had been flushed, which meant we had to get lucky that that trace was sampled, and that that worker didn't OOM.

We're going to enable partial flushing on our APIs today, so I'll let you know if we see the memory leaks stop. Otherwise we'll try to enable profiling to see if we can track down where the leak is exactly coming from.

> Can you explain to me your use-case for configuring it at runtime? It sounds like you want to dynamically control whether it is enabled or not depending on memory usage (or... something like that?).

This is mostly a nice-to-have, in that it would let us hook this config up to our configuration management system and roll out changes to live hosts to see how it impacts metrics and memory usage without having to completely restart them all.

> In general my largest concern is still around how partial flushing interacts with our system, it can cause undesired side effects in how metrics are computed. Not saying this should be a hard blocker for us exposing an option, just want to be forward with where my apprehensions are in making it easy to configure.

Yeah that's understandable. I think though having a disclaimer that this happens might be good enough? As an end user I'd rather have a documented flag that clearly states what it does and any drawbacks it might have, instead of having to think to search Github and find this issue. We found this flag when digging through the code to figure out why enabling dd-trace led to unbounded memory usage on hosts, and figuring out how to turn it on wasn't that hard, so it's only that someone questioned why this wasn't documented that led us to this issue.

This is also easily configurable in dd-trace-java and included in the documentation, but it doesn't discuss this drawback so maybe worth updating those docs as well.

**Comment by Kyle-Verhoog** [comment]
We missed closing this out but we added support for partial flushing with the `DD_TRACER_PARTIAL_FLUSH_ENABLED`/`DD_TRACER_PARTIAL_FLUSH_MIN_SPANS` environment variables and the `partial_flush_enabled`/`partial_flush_min_spans` arguments to `tracer.configure()`
