### ISSUE TITLE
django opentracing: disconnected middleware spans with new django integration

### ISSUE THREAD

**Issue by majorgreys** [DataDog/dd-trace-py#1198]
When updating the [python/opentracing/django](https://github.com/DataDog/trace-examples/tree/master/python/opentracing/django) example to the new Django integration (#1161), we gain visibility but the spans generated from the middleware are not part of the same trace.

Before update:

![image](https://user-images.githubusercontent.com/155673/74256865-0c2f1500-4cc2-11ea-945a-810017448f71.png)

After update:

![image](https://user-images.githubusercontent.com/155673/74256903-19e49a80-4cc2-11ea-80c9-3a2153b77b39.png)

But middleware spans are detached from the `django.request` root:

![image](https://user-images.githubusercontent.com/155673/74257112-6039f980-4cc2-11ea-8aae-b6b508b5be2c.png)

To reproduce:

* Update `ddtrace`: `git+https://github.com/DataDog/dd-trace-py.git@f0746c39c4ef9c52b9a7590f7daf0e6c7c613dc4#egg=ddtrace[opentracing]`
* Run server with Django integration: `ddtrace-run python manage.py runserver 8000`
* Open `http://localhost:8000/client/simple`

**Comment by Kyle-Verhoog** [comment]
I ran the scenario again with the latest version of ddtrace (0.50) and wasn't seeing the bunched up requests 

![image](https://user-images.githubusercontent.com/6321485/127371184-bd24a28a-bfc4-4fb8-aab2-abb3df71a77a.png)

The trace doesn't look quite right but this issue seems to have been addressed.
