### ISSUE TITLE
How to migrate patch_db()?

### ISSUE THREAD

**Issue by Siecje** [DataDog/dd-trace-py#1255]
I'm upgrading from `0.33.0`. `0.34.0` contains breaking changes. Since datadog only runs in production I didn't know about them until it was deployed.

Ideally the major version should have changed but at least the release notes should have used the term "breaking changes". When I read it, it seemed there was a new Django integration and the old way would still work. https://github.com/DataDog/dd-trace-py/releases/tag/v0.34.0

I'm trying to figure out how to migrate the `patch_db()` function.

```
from ddtrace.contrib.django.db import patch_db
patch_db(tracer)
```

I see there is now an `instrument_dbs()` function. Should I use that?

https://github.com/DataDog/dd-trace-py/commit/f0746c39c4ef9c52b9a7590f7daf0e6c7c613dc4#diff-57e69015e02fa12210f1e76739d16862R102-R116

**Comment by majorgreys** [comment]
Thank you for point this out @Siecje. 

Before 0.34.0, the Django integration was configured using `settings.INSTRUMENT_DATABASE` in https://github.com/DataDog/dd-trace-py/blob/v0.33.0/ddtrace/contrib/django/patch.py#L72. The migration to 0.34.0 handles this configuration still. 

However, as you point out, a lot has changed with the new Django integration under the hood. 

We try our best with each release to not break the publicly documented API for the tracer and configuring the tracer for our supported integration. I'm sorry this update introduced breaking changes for you. Can you explain why you opted to use the `patch_db` function in this way rather than the `settings.INSTRUMENT_DATABASE`? We want to make sure that we address any friction that developers have had with the configuring the tracer and integrations.

**Comment by Siecje** [comment]
`INSTRUMENT_DATABASE` was `False`. I don't know why `patch_db()` was used. I wasn't able to find documentation on it.

This is the previous config.

```Python
from ddtrace import tracer
from ddtrace.contrib.django.db import patch_db

tracer.configure(enabled=True)

INSTALLED_APPS += ("ddtrace.contrib.django",)

# Performance analytic settings from datadog
DATADOG_TRACE = {
    "TAGS": {"env": RUNNING_ENV},
    "ENABLED": True,
    "AUTO_INSTRUMENT": False,
    "INSTRUMENT_DATABASE": False,
    "INSTRUMENT_CACHE": False,
    "INSTRUMENT_TEMPLATE": False,
    "AGENT_HOSTNAME": os.environ.get("DD_AGENT_HOST"),
}

# only enable trace for db
patch_db(tracer)

```

This is the new config.

```Python
from ddtrace import tracer
# Performance analytic settings from datadog
tracer.configure(enabled=True, hostname=os.environ.get("DD_AGENT_HOST"))
tracer.set_tags({"env": RUNNING_ENV})
```

I hope this is equivalent.

**Comment by majorgreys** [comment]
@Siecje Are you using `ddtrace-run` for enabling Django tracing? If not, you'll want to follow the instructions for the manual instrumentation. Either way, you can use the environment variables `DD_TRACE_GLOBAL_TAGS` and `DD_AGENT_HOST` to configure the tracer.

https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/django/__init__.py#L6

**Comment by Siecje** [comment]
I am not using `ddtrace-run`. So my new settings.py should have this?


```Python
from ddtrace import patch_all, tracer
# Performance analytic settings from datadog
tracer.configure(enabled=True, hostname=os.environ.get("DD_AGENT_HOST"))
tracer.set_tags({"env": RUNNING_ENV})
patch_all()
```

**Comment by majorgreys** [comment]
Yes, that should get you Django tracing enabled with the default behavior including the `env` tag set. Please confirm that it works on your end.
