### ISSUE TITLE
distributed tracing support for ContextVarsScopeManager

### ISSUE THREAD

**Issue by anandhs** [DataDog/dd-trace-py#1367]
`ddtrace==0.33.0`
`opentracing==2.3.0`
`sanic==19.12.2`

I have a `sanic` application with custom tracing for which I am using `opentracing` along with `ContextVarsScopeManager` as the scopeManager. 

I am trying to use [`Tracer.extract`](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/opentracer/tracer.py#L287) to extract distributed trace headers from the request.  I have confirmed that the headers do exist. 

### To Reproduce:

On a sanic application's request interceptor, try capturing the distributed trace headers like this 

```
from opentracing.scope_managers.contextvars import ContextVarsScopeManager
from opentracing.scope_managers.asyncio import AsyncioScopeManager
from ddtrace.opentracer import Tracer, set_global_tracer
from ddtrace.opentracer.propagation import HTTPPropagator
from ddtrace.opentracer.utils import get_context_provider_for_scope_manager


headers = {'host': 'localhost:8080', 'x-datadog-trace-id': '6115812197340406545', 'x-datadog-parent-id': '3252172679056420642', 'x-datadog-sampling-priority': '1'}
_tracer = Tracer("myapp", config={}, scope_manager=ContextVarsScopeManager)
span = _tracer.start_span("web.request")

propagator = HTTPPropagator()
ctx = propagator.extract(headers)

# prints ddtrace.provider.DefaultContextProvider 
print(get_context_provider_for_scope_manager(_tracer.scope_manager)) 

```
I suspect this is due to `ContextVarsScopeManager` being unsupported here 

https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/opentracer/utils.py#L5 

I would be happy to submit a patch if someone can confirm this is an issue.

**Comment by Kyle-Verhoog** [comment]
Hi @anandhs!

What is the erroneous behaviour you're seeing? Is it failing to extract the headers or is not activating the propagated trace information? Does the `ctx` variable in your example contain the correct data?

I'm not sure if your example code is 100% complete but it seems like `tracer.extract` is not being used (which would activate the context). Else, in your example you would still need to activate the context since the `HTTPPropagator` does not do this itself.

```python
from opentracing import Format
_tracer.extract(Format.HTTP_HEADERS, headers)  # should extract and activate the context
```

The opentracing `ContextVarsScopeManager` does actually correspond to the ddtrace `DefaultContextProvider`, which uses ContextVars under the hood (for Python 3.7+), so should be no issue there.

**Comment by anandhs** [comment]
Hi @Kyle-Verhoog , thanks. using the suggested code, helped me move forward. I will close this issue.
