### ISSUE TITLE
django orm should not trace if the underlying db connection is traced

### ISSUE THREAD

**Issue by clutchski** [DataDog/dd-trace-py#141]
otherwise the same span can be traced multiple times.

**Comment by palazzem** [comment]
We don't have a clean way to double check if the instrumentation is active or not, mostly because it depends on execution order. Because of that, we added new settings to manually disable the ORM, Cache and Template instrumentation: https://github.com/DataDog/dd-trace-py/pull/314

Closing since that PR address this issue.
