### ISSUE TITLE
[feature request] grpc client traces respect service name

### ISSUE THREAD

**Issue by jfmyers9** [DataDog/dd-trace-py#1528]
Hi folks,

When patching GRPC, it seems that the service name is hardcoded to [`<service>-grpc-client`](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/grpc/patch.py#L20-L25). Is it possible to change this behavior so that it is just `<service>`? At the moment this is creating multiple APM services in DataDog for a single service.

Thoughts?

**Comment by Kyle-Verhoog** [comment]
Hey @jfmyers9!

Yep, the service name really shouldn't be including the grpc-client suffix. I believe it's like that due to some backwards compatibility unfortunately. We're looking into how we can deprecate this and unify the service names across integrations.

I was going to recommend setting `ddtrace.config.grpc.service_name = "<service>"` but realized that this probably won't work because we [assign the service at patch-time](https://github.com/DataDog/dd-trace-py/blob/9de0ba2ebb16b55767527066c8d4dd07e039dc26/ddtrace/contrib/grpc/patch.py#L43), which means you won't be able to override it after the integration is patched, which is a bug 🤦‍♂️. I've added a fix for this in #1530 which will land in `0.40.0`.

So you'll be able to override the default behaviour with:

```
ddtrace.config.grpc.service_name = "<service>"
```

or with the environment variable `DD_GRPC_SERVICE_NAME="<service>"`.

However, I realize that this is still kind of cumbersome and you'd have to specify the service name twice which isn't ideal. I'm going to propose to the team that we add a `DD_GRPC_USE_DD_SERVICE=true|false` (or similar) configuration option to force the integration to use the modern semantics of service naming.

**Comment by jfmyers9** [comment]
That sounds awesome. Thanks for getting to this so fast.

**Comment by jfmyers9** [comment]
I think this has been fixed as of `v0.40.0`. Thanks!
