### ISSUE TITLE
Please support fastapi

### ISSUE THREAD

**Issue by venthur** [DataDog/dd-trace-py#1616]
Please consider adding [fastapi](https://github.com/tiangolo/fastapi) to the list of supported web frameworks. It currently has around 20k stars and 1.3k forks on github, so it is certainly a popular and widely used library.

### Which version of dd-trace-py are you using?

0.41.0

### Which version of the libraries are you using?

fastapi[all]==0.60.1

### How can we reproduce your problem?

When you currently use ddtrace like with fastapi like so:

```bash
$ ddtrace-run uvicorn some.app:app --host 0.0.0.0
```

### What is the result that you get?

Nothing really happens. If you happen to use SQL or anything else recognized by ddtrace than this will pop up in datadog, but the actual fastapi app will not show up a service.

### What is the result that you expected?

The app should how up under Datadog / APM / Services.

**Comment by jmandt** [comment]
@venthur I am also using fastapi and cannot get it to work, although I think due to another issue. 

As far as I understood, FastAPI is based on Starlette and implements the ASGI specification, so you can use any ASGI middleware - see [reference](https://fastapi.tiangolo.com/advanced/middleware/). 

Also, you can find documentation [here](http://pypi.datadoghq.com/trace/docs/web_integrations.html#asgi) on how to send traces to the datadog agent.

**Comment by venthur** [comment]
There's two things: you [don't have to go async](https://fastapi.tiangolo.com/async/) using fastapi, but you **can** if you want. But more importantly: dd-trace [aims to support a wide range of libraries](http://pypi.datadoghq.com/trace/docs/#supported-libraries) out of the box. Given fastapi's popularity, I think it is fair to assume it should be supported as well.

**Comment by cloudrave** [comment]
We are using FastAPI, and Datadog APM works as expected.

```python
from ddtrace_asgi.middleware import TraceMiddleware

app.add_middleware(
    TraceMiddleware,
    service=os.environ.get("DATADOG_SERVICE_NAME", SERVICE_NAME),
)
```

**Comment by majorgreys** [comment]
Thank you @cloudrave for explaining how to manually add the ASGI middleware. We have added the ASGI middleware to the library in 0.41.0:

http://pypi.datadoghq.com/trace/docs/web_integrations.html#asgi

We do have plans to improve support for Starlette and FastAPI in the near future.

@venthur Does that address your use case?

**Comment by inikolaev** [comment]
Thanks for adding `TraceMiddleware`, but I would still vote to support FastAPI or Starlette directly.
Current middleware works good on many use-cases, but unfortunately it cannot handle URLs with path parameters properly, since there's no standard way to expose routes in ASGI scope.

Here's an example of what I mean: consider you have an endpoint defined like this:

```python
@router.get(path='/users/{id}')
def get(payment_id: int) -> JSONResponse:
    pass
```

Whenever there are requests to this endpoint, e.g. `GET /users/1` and `GET /users/2`, they will be reported as two distinct resources in DataDog, so it wouldn't be possible to gather aggregated statistics. Instead it should be reported as `GET /users/{id}`.

In our project I had to add the following change in order to support this:

```python
def __enrich_span(self, span: Span, scope: Scope, method: str) -> None:
    if "router" in scope:
        path = None
        routes = getattr(scope["router"], "routes", [])
        for route in routes:
            match, _ = route.matches(scope)
            if match == Match.FULL:
                path = route.path
                break
            elif match == Match.PARTIAL and path is None:
                path = route.path

        if path is not None:
            span.resource = f"{method} {path}"
```

Which is called before `span.finish()` to set correct resource name. 

As I said, this is Starlette specific and might not work for other ASGI frameworks, but maybe this will help someone else.

**Comment by venthur** [comment]
The middleware does not quite work yet. When using the `app.on_event` decorator as described [here](https://fastapi.tiangolo.com/advanced/async-sql-databases/?h=+on_event), ddtrace-run crashes with:

```
    ...
    @app.on_event("startup")                                                                                                                                                                                         
AttributeError: 'TraceMiddleware' object has no attribute 'on_event' 
```

**Comment by venthur** [comment]
Is it released already? 0.46 doesn't seem to work still.

**Comment by Yun-Kim** [comment]
Hi @venthur, the above PR adding the FastAPI integration has been merged and will be included in the next release (0.47.0).

**Comment by expobrain** [comment]
@Yun-Kim is there a date for the 0.47.0 release yet?

**Comment by Yun-Kim** [comment]
Hi @expobrain, we're planning on releasing 0.47.0 before the end of next week - [here](https://github.com/DataDog/dd-trace-py/issues/2066) is another link to follow specifically regarding the upcoming release.

**Comment by LivioMirandaJr** [comment]
Sorry bringing this up here, I don't know if it was better opening a new issue.

Does DataDog accept path parameters yet? When creating a metric using trace.fastapi the only option for resource_name is:

`resource_name:"POST /seller/{seller_id}/pvt/orderForms/simulation"`
But I wanted to query specific seller_id's, is it possible?

**Comment by Kyle-Verhoog** [comment]
hey @LivioMirandaJr, querying the specific seller_id in the resource name isn't possible as cardinality for resource names is an issue. Resource names are used to aggregate performance and error information about web applications so it's important that they get aggregated.

What you could do instead is set the seller id as a tag on the root span ([`tracer.current_root_span()`](https://ddtrace.readthedocs.io/en/stable/api.html#ddtrace.Tracer.current_root_span)) and then use the UI to create a facet: https://docs.datadoghq.com/tracing/trace_explorer/facets/
