### ISSUE TITLE
Add tag for resource name variables

### ISSUE THREAD

**Issue by oryband** [DataDog/dd-trace-py#1617]
I'm using aiohttp and would like to add specific resource name variables as tags, for example:
```python
from aiohttp import web

app = web.Application(...)
app.router.add_get('/some/endpoint/{tag_this}/', my_handler)
```
I'll be using this to track per resource name latency and request counts. Is this possible? If so, how?

Followup question: Assuming it's possible, is it possible to only trace specific resource name variables? For example:
```python
app.router.add_get('/some/endpoint/{tag_this}/{but_not_this}/', my_handler)
```

Thank you

**Comment by Kyle-Verhoog** [comment]
@oryband we're just combing through our old issues and somehow we missed replying to you, sorry about that!

Were you able to find the solution you were looking for?

You'd be able to accomplish this be setting a custom tag and then creating a facet in the UI. With the facet you should be able to get the trace metrics like latency and count.

```python
from ddtrace import tracer

# In your handler
span = tracer.current_span()
if span:
    span.set_tag("specific-endpoint", "{tag_this}")
```

I'm going to close as this issue is quite old (sorry again!) Please reopen this issue if this doesn't work!
