### ISSUE TITLE
Is there a way to turn off logging for trace issues?

### ISSUE THREAD

**Issue by kuhnboy** [DataDog/dd-trace-py#1838]
### Which version of dd-trace-py are you using?
0.43.0

### Which version of the libraries are you using?

ddtrace==0.44.0
  - intervaltree [required: Any, installed: 3.1.0]
    - sortedcontainers [required: >=2.0,<3.0, installed: 2.3.0]
  - protobuf [required: >=3, installed: 3.14.0]
    - six [required: >=1.9, installed: 1.15.0]
  - tenacity [required: >=5, installed: 6.2.0]
    - six [required: >=1.9.0, installed: 1.15.0]

### How can we reproduce your problem?

When running data dog agent as a sidecar in ECS, the agent may startup slower or terminate faster than dd-trace. During this time we get a bunch of errors regarding: "Failed to send traces to Datadog Agent at http://localhost:8126: [Errno 111] Connection refused".

How can I turn off logging as this is somewhat just noise to me since it may happen on scale events and deployments?

**Comment by Kyle-Verhoog** [comment]
Hi @kuhnboy! You can use the `DD_TRACE_STARTUP_LOGS=0` to disable the logging. Due to feedback we are changing the default for startup logs to be disabled in the next release (#1717).

**Comment by kuhnboy** [comment]
You guys rock. Thanks!

**Comment by hilsenrat** [comment]
@kuhnboy Did your issue was indeed resolved? I can still see an errors like `ERROR:ddtrace.internal.writer:failed to send traces to Datadog Agent at ...`, even with the latest version.  
If I set `DD_TRACE_STARTUP_LOGS` to `true`, this message also appears: `DATADOG TRACER DIAGNOSTIC - Agent not reachable at x.x.x.x:8126. Exception raised: [Errno 111] Connection refused`, but in addition to the above message.  

@Kyle-Verhoog Should I open a new issue? Is the fact that I still get this log printed is a bug or the intended behaviour?

**Comment by Kyle-Verhoog** [comment]
@hilsenrat this particular issue was related to these logs showing up during library initialization in which the library would try to send a payload to the agent and resulting in some noise. 

If you're seeing those errors right now without setting `DD_TRACE_STARTUP_LOGS` then it's likely a legitimate error where the library cannot reach an agent when submitting traces. If you think that the log messages are wrong please open up a new issue! 🙂
