### ISSUE TITLE
wrap API defaults are broken

### ISSUE THREAD

**Issue by jontonsoup** [DataDog/dd-trace-py#189]
It appears that the wrap api defaults do not work with the UI. 

I need to do this for it to work: 
```
@tracer.wrap(name=DATADOG_SETTINGS["TRACER_SERVICE_NAME"],service=DATADOG_SETTINGS["TRACER_SERVICE_NAME"], resource="FUNCTION_NAME")
```

**Comment by palazzem** [comment]
Actually it mostly depends on the instrumented code. If the `tracer.wrap()` isn't added to a function that is already part of a trace, some fields like the `service` may not have a value. In that case the agent is going to drop that trace.

Here I think that the `wrap()` decorator is working correctly as expected. What we did (and what we're continuing to do) is providing better defaults in general.

Because the issue here is not completely related to the wrap API, I'm going to close that issue for the moment! Thanks for reporting that (and sorry for a so late answer).
