### ISSUE TITLE
TypeError: can not serialize 'Composed' object

### ISSUE THREAD

**Issue by adamchainz** [DataDog/dd-trace-py#2001]
### Which version of dd-trace-py are you using?

0.46, having upgraded from 0.43

### Which version of the libraries are you using?

`protobuf==3.14.0`
`tenacity==6.3.1`

and relevantly:

`psycopg2-binary==2.8.6`

### How can we reproduce your problem?

Send a trace with a psycopg2

### What is the result that you get?

On Sentry after deploying the ddtrace upgrade, immediately got:

`TypeError: can not serialize 'Composed' object`

This looks like a recurrence of #732.

Stack frames:

ddtrace/internal/_encoding.pyx in ddtrace.internal._encoding.Packer._pack at line 263
ddtrace/internal/_encoding.pyx in ddtrace.internal._encoding.Packer._pack at line 187
ddtrace/internal/_encoding.pyx in ddtrace.internal._encoding.Packer.pack at line 269
ddtrace/internal/_encoding.pyx in ddtrace.internal._encoding.Packer.pack at line 272
ddtrace/internal/_encoding.pyx in ddtrace.internal._encoding.MsgpackEncoder.encode_trace at line 300
ddtrace/internal/_encoding.pyx in ddtrace.internal._encoding.MsgpackEncoder.encode_trace at line 299
ddtrace/internal/writer.py in write at line 257

### What is the result that you expected?

No error.

**Comment by majorgreys** [comment]
Are you by any chance using the deprecated connection factor rather than patching as described in https://ddtrace.readthedocs.io/en/stable/integrations.html#module-ddtrace.contrib.psycopg? The deprecated approach is not converting the query object to a string:

https://github.com/DataDog/dd-trace-py/blob/97140a6f72b241982454feac64816f57b6ba6bc1/ddtrace/contrib/psycopg/connection.py#L53

**Comment by adamchainz** [comment]
No we use plain `ddtrace-run` and let it call `patch_all()`.

**Comment by majorgreys** [comment]
I am adding an encoding test to psycopg in #2003 which is passing. Mind taking a look over the test case? Maybe we are still missing something.

https://github.com/DataDog/dd-trace-py/pull/2003/files#diff-41f07c055df91a25d2f3c15e89367264e67c74167119355a7b1f8f9da3bf9546R297-R313

**Comment by adamchainz** [comment]
Hmm. Looking a little closer at the crash it happened during our Django migrations phase, and *may* have been triggered by this:

```
cursor.execute(
            "SET statement_timeout=%s",
            (timeout_milliseconds,),
        )
```

Or by this:

```
cursor.execute(
    """
    CREATE OR REPLACE FUNCTION trim_postcode (postcode text) RETURNS text AS $$
    declare
      trimmed_postcode text;
    BEGIN
      trimmed_postcode := REPLACE(postcode, ' ', '');
      IF LENGTH(trimmed_postcode) > 5 THEN
        RETURN SUBSTRING(trimmed_postcode, 1, LENGTH(trimmed_postcode) - 3);
      ELSE
        RETURN trimmed_postcode;
      END IF;
    END; $$
    LANGUAGE PLPGSQL;
    """
)
```

Hard to know because Sentry couldn't capture the line within our code, only within the datadog thread. But it did capture queries in its "breadcrumbs" feature, up to the first one there.

Of course those might be completely off if the breadcrumbs are wrong, and I think they sometimes are.  We do directly use the `pscyopg2.sql` classes later in the migration process, with some formatting calls like:

```
from psycopg2 import sql

sql.SQL("SELECT {x}").format(x=sql.Literal("x"))
```

Hopefully one of these can reproduce the crash.

**Comment by majorgreys** [comment]
@adamchainz Could you try the branch in #2229 to see if this resolves the problem you are having? I have not been able to reproduce this issue in a test though wanted to share on potential mitigation before proceeding down this path.

**Comment by adamchainz** [comment]
I haven't had time to check this out. It's a little hard for us since it only happens in the production environment. Did you try testing the example code as above?

**Comment by majorgreys** [comment]
@adamchainz I have been looking at this recently and think I might know why this is occurring for you and others.

You are using Django here and I assume you have not explicitly disabled the Django DB instrumentation that our integration provides. Does this problem go away for you if you disable that instrumentation with `ddtrace.config.django['instrument_databases'] = False`? This is described in [the Django integration configuration](https://ddtrace.readthedocs.io/en/stable/integrations.html#id21).

The Django DB instrumentation creates a span in addition to the span created any dbapi-compliant library that has been patched as well. While the psycopg integration [coerces](https://github.com/DataDog/dd-trace-py/blob/d5b84311858870411c4a4c13486dc32b8e29477f/ddtrace/contrib/psycopg/patch.py#L60) a composed query the db span that is created by Django will not perform the same coercion when it's setting the span resource. This is because Django [wraps](https://github.com/DataDog/dd-trace-py/blob/d5b84311858870411c4a4c13486dc32b8e29477f/ddtrace/contrib/django/patch.py#L85) creates a cursor for its db connection using the `TracedCursor` from the `dbapi` integration, [setting the resource](https://github.com/DataDog/dd-trace-py/blob/d5b84311858870411c4a4c13486dc32b8e29477f/ddtrace/contrib/dbapi/__init__.py#L62) to the `query` without any coercion. 

If this is the source of your issue, we could resolve this by performing such coercions in the Django DB instrumentation (which might be tricky since we'd have to handle multiple backends) or we just avoid creating an additional span for the cursor call if that cursor has already been wrapped because of a db integration. I'm inclined to pursue the latter option if this is in fact the source of this issue.

**Comment by majorgreys** [comment]
I have opened an issue for discussion of a proposal to resolve the issue with Django db instrumentation: #2438

**Comment by adamchainz** [comment]
> Does this problem go away for you if you disable that instrumentation with `ddtrace.config.django['instrument_databases'] = False`?

I just got around to testing this, and yes, the problem does go away with that change.

I tested with this one-liner:

`ddtrace-run python manage.py shell -c 'from django.db import connection; from psycopg2 import sql; cursor = connection.cursor(); cursor.execute(sql.SQL("SELECT 123"))'`
