### ISSUE TITLE
Distributed tracing of aiobotocore calls?

### ISSUE THREAD

**Issue by Padwicker** [DataDog/dd-trace-py#2039]
### Which version of dd-trace-py are you using?
ddtrace = "0.45.0"

### Which version of the libraries are you using?
aiobotocore==1.1.2
aiohttp==3.7.1
aioitertools==0.7.0
async-timeout==3.0.1
attrs==20.2.0
boto3==1.14.44
botocore==1.17.44
certifi==2020.6.20
chardet==3.0.4
docutils==0.15.2
idna==2.10
jmespath==0.10.0
multidict==5.0.0
oauthlib==3.1.0
python-dateutil==2.8.1
requests==2.24.0
requests-oauthlib==1.3.0
s3transfer==0.3.3
six==1.15.0
tpd-python-lib==0.1.51
typing-extensions==3.7.4.3
urllib3==1.25.11
wrapt==1.11.2
yarl==1.6.2

### How can we reproduce your problem?
Patch an app with aiobotocore Lambda calls. All Lambdas being called have  datadog tracing enabled.

### What is the result that you get?
The calls show up in the trace, but the trace is not picked up by other Lambdas.

### What is the result that you expected?
Traces continued across Lambdas.

Distributed tracing is possible with botocore as mentioned [here](https://ddtrace.readthedocs.io/en/stable/integrations.html#botocore). Would it be possible to have this enabled for aiobotocore? Thanks.

**Comment by jwthomp** [comment]
I'm seeing the same issue. I believe it is failing for invocation types that are not RequestResponse vs Event. I haven't proven this out yet though.

**Comment by jwthomp** [comment]
I'm having the same issue. What I am seeing is that the client context is not being sent over with the lambda invocation. Neither are the headers having the trace-id added to them. (datadog_lambda looks for trace_id, parent_id, and sampling priority either in headers passed with the event, otherwise it looks in the context for a client_context dict. 

I'm seeing neither passed to a lambda when patching aiobotocore and invoking the lambda.
