### ISSUE TITLE
ddtrace-run doesn't set resource name properly for request patch.

### ISSUE THREAD

**Issue by yxing999** [DataDog/dd-trace-py#2241]
### Which version of the libraries are you using?
0.46.0
### What is the result that you get?
<img width="646" alt="Screen Shot 2021-03-26 at 15 46 22" src="https://user-images.githubusercontent.com/37628246/112700105-9eed2d80-8e4a-11eb-82fd-ec75650d40f5.png">
### What is the result that you expected?
Set url or something identifiable as resource.

If I am reading right, the span was generated at https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/requests/connection.py#L63. So is it possible to add something to set the resource name?

**Comment by Kyle-Verhoog** [comment]
Hi @yxing999, sorry for the delay!

We don't set the resource to be the URL at the moment because the cardinality could be very high which results in a poor experience with the service page - although I agree that the default behaviour now is not great either.

You might be able to solve your use-case by using the url tag that is attached to the requests spans. This documentation here might be helpful: https://docs.datadoghq.com/tracing/guide/add_span_md_and_graph_it/.

If you still can't achieve the functionality after reading through the above please share your use-case with us and we'd love to discuss further 🙂

**Comment by Kyle-Verhoog** [comment]
Going to close this issue now but feel free to reopen if the work-around here is insufficient!
