### ISSUE TITLE
Make profiling code installable as a pip extra instead of by default

### ISSUE THREAD

**Issue by xtaje** [DataDog/dd-trace-py#2247]
### Which version of dd-trace-py are you using?
Affects versions > 37.0

### Which version of the libraries are you using?
Affects versions > 37.0

### How can we reproduce your problem?
Attempt to pip install ddtrace in a container that does not have gcc or linux headers installed eg, : alpine linux, debian-slim, ...

### What is the result that you get?
The installation will fail during creation of the wheel when the installer attempts to compile code for profiling

### What is the result that you expected?
Installation does not depend on having a dev tools installed.  If the profiling features are installable separately as a pip extra (`pip install ddtrace[profiling]`), then users who aren't using profiling can install ddtrace as a pure python package without all the additional baggage.

Having to install a compiler etc. makes builds slower and more complicated for people using containers.

**Comment by brettlangdon** [comment]
@xtaje thank you for reaching out.

We have [pre-built wheels](https://pypi.org/project/ddtrace/0.47.0/#files) available for a bunch of systems (including aarch64 since version 0.45.0).

Unfortunately it isn't just the profiler which requires building C code, so I'd love to know more about your system setup so we can do whatever we can to make sure to have wheels available to ease the installation process.

Can you share some more information about the system you are installing on?

What version of `pip` are you using? (`ddtrace` requires `pip>=18` to install our wheels).

**Comment by xtaje** [comment]
I see, it looks like a bunch of internals are cythonized.

We are using alpine + python2.7 + musl + pip 20.2.3.

**Comment by brettlangdon** [comment]
@xtaje sorry for the long delay getting back to you here.

I have opened up #2354 to help clarify installation instructions on Alpine.

The build dependencies that are needed to build the tracer are:

> apk add gcc musl-dev linux-headers

These are needed until [PEP-656](https://www.python.org/dev/peps/pep-0656/) is implemented and available for us to publish musl linux wheels.

I am planning to create and pin a new issue related only to installation on Alpine and tracking PEP-656, so I will close this in favor of that one. Please feel free to re-open if you are still experiencing issues or feel the new issue does not properly capture your issue.

**Comment by brettlangdon** [comment]
#2355 is the more general issue opened.
