### ISSUE TITLE
Proposal: Break package into multiple packages

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/dd-trace-py#2442]
Right now we ship one single `ddtrace` package that includes everything.

What if instead we broke out integrations, the core of the tracer, and profiler into their own packages.

This would allow us to have separate semver versions for integrations vs the profiler vs the core of the tracer.

We need to figure out:

- Is this something that we want?
- What packages would we create?
- What would be the dependency between them?
- What is the relationship of versions between them?

**Comment by emmettbutler** [comment]
This is tracked in our team's internal backlog and is also under discussion between multiple Client Libraries teams within Datadog. This issue has been open for a while and garnered a few thumbs-up reactions, which is a useful signal we can apply toward prioritizing this work. I'm going to close this ticket because I think it has served its purpose and the effort is tracked elsewhere.
