### ISSUE TITLE
How to know where in the code a span was started

### ISSUE THREAD

**Issue by wk8** [DataDog/dd-trace-py#2514]
### Which version of dd-trace-py are you using?
0.49.2

### Which version of pip are you using?
21.1.2

### Which version of the libraries are you using?

N/A

### How can we reproduce your problem?

Not a bug, feature request: I'd like to be able to know immediately where a given span was started in the code; that is, I'd like to have a "tag" on all of my apps' spans telling me which file and line number `with tracer.trace(...):` was called (or if that's from an integration, then which file and line number in my app code made a call that eventually started a span).

Two questions:
1. is there currently a way to do this?
2. If not, would you be open to a PR adding a config parameter to add this tag to all spans? That could be achieved by considering the backtrace when calling `ddtrace.tracer.Tracer.start_span`, and taking the latest entry of that stacktrace that's outside of the `ddtrace` package.

If that sounds acceptable to you, I'd be happy to submit a PR for that.

**Comment by brettlangdon** [comment]
Hey @wk8 thanks for reaching out!

1. No, there is currently no way to do this, unless you do this manually (`span.set_tag("code.file", __file__)`, ...) for custom instrumentation
2. This is a feature request we have gotten in the past. I am checking internally to see if we've made any progress on it. For integrations, would you want the file/line of code in the integration that is being called, or where in your code the call was initiated from?

**Comment by wk8** [comment]
Thanks @brettlangdon for the super quick response! :)

> 2. This is a feature request we have gotten in the past. I am checking internally to see if we've made any progress on it. For integrations, would you want the file/line of code in the integration that is being called, or where in your code the call was initiated from?

The latter, hence my proposal above to just take the stacktrace when calling ddtrace.tracer.Tracer.start_span, and taking the latest entry of that stacktrace that's outside of the `ddtrace` package.

If that sounds reasonable to you, happy to make a PR, let me know, thanks!

**Comment by brettlangdon** [comment]
> The latter, hence my proposal above to just take the stacktrace when calling ddtrace.tracer.Tracer.start_span, and taking the latest entry of that stacktrace that's outside of the `ddtrace` package.

If I remember correctly the issue we had when looking at this is, we don't know which code is owned by the user vs some other library.

Sometimes we also patch inner functions in our integrations (not just the public API), which would make the caller of us the integration. An example being, `requests`, if we patch `requests.requests` instead of `request.get`, then the first non-ddtrace frame of the traceback would be `requests.get` instead of your code.

We could probably be smarter, we know we are in a `requests` integration, so just ignore anything in `requests` and get whatever in the backtrace is before `requests`.

However, where that also is potentially an issue is wrapper libraries. If you take Django models which construct and call `psycopg2`, if we look in the backtrace for the first non`psycopg2` frame, we might end up in Django instead of your code. We might need to keep track of all libraries which use a specific integration?


What do you think? It has been a minute since we've thought about/investigated this so I am mostly just trying to re-remember issues/approaches we looked at in the past.

**Comment by wk8** [comment]
Mhm I didn't think of that.

How about keeping it dumb then, and pushing the whole stacktrace? Users can then decide what's relevant or not?

Alternatively, users could provide a list of regexes to determine which packages belong to them, but that feels very clunky :/

**Comment by brettlangdon** [comment]
@wk8 have you tried our profiling product yet? wondering if there is enough overlap there for the data you are looking for there

**Comment by wk8** [comment]
We use it too, but it'd be really nice to be able to know straight away "oh okay this DB query is from here, this HTTP request is from there".

I take it you don't like the idea of pushing the whole stacktrace?

**Comment by brettlangdon** [comment]
> I take it you don't like the idea of pushing the whole stacktrace?

Yeah, I am really hesitant to take this approach since it is costly, both on collecting and on transmitting.

Taking the whole stacktrace probably makes the most sense to ensure you definitely get the data you need, but it is probably best to be able to apply some kind of heuristic to it on when to collect.

For example, some code paths don't change, so it wouldn't be bad to collect once and submit once. Or maybe we do some kind of sampling, collect a stack trace on every X traces to reduce the impact. Maybe it is opt-in on specific spans only?

I wonder if we can optimize with overlapping stack traces, can we collect just the leaf node stacktraces? e.g. a span finished which didn't have any children. Or maybe collect every frame up until your parent spans frame?

**Comment by wk8** [comment]
Indeed this is a more complicated problem that it seems at first glance :( no good solution for now, will post here if something comes to mind. Thanks!

**Comment by brettlangdon** [comment]
@wk8 please do! We'll keeping thinking on this as well.

**Comment by majorgreys** [comment]
Nothing new on our side but if there are any new discussion this issue can be reopened.

**Comment by bepetersn** [comment]
I am also interested in such a feature... and I was just thinking about attempting to implement it myself (add a tag to the span), but wanted to check here. 

I doubt this is extremely helpful, but I have tried to solve a specific problem similar to this before, outside the context of datadog. It sounded like the OP was looking for more of a general solution than I am, though. I would really like to see this specifically for DB queries, i.e. I don't care about an arbitrary span. What I settled on was two-fold. 

1. Take the first frame (filename / lineno) off the top of the stack that wasn't prefixed with `sys.prefix` or `sys.base_prefix`, i.e. non-stdlib and non-virtualenv package. 
2. This doesn't always work if there is an "internal" caller, which sounds similar to the tricky case you were thinking about. In my case, it was a middleware doing valid work, ... I handled that in a way that might not be generalizable, but it seems like in datadog's case you could simply do nothing if no user code is found... it wouldn't help in that case, but it could be better than nothing.

Just some thoughts.
