### ISSUE TITLE
Consider releasing a major version (1.0.0)

### ISSUE THREAD

**Issue by Gidgidonihah** [DataDog/dd-trace-py#2539]
0 version is [for initial development](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase).

I think it's safe to say that dd-trace-py is in use in production at this point, so there should [probably be a major version](https://semver.org/#how-do-i-know-when-to-release-100)

Using a 0 version is technically correct semver because
> Anything MAY change at any time. The public API SHOULD NOT be considered stable.

However, practically, that's not great at this point. 

As en example, I'll lay out the problems we run into with v0 ddtrace:

We have an internal python library (let's call it `pynternal`) that we maintain that relies upon semver. We use poetry as our dependency manager. `pynternal` was last updated when the latest `ddtrace` version was `0.48.3`. Awesome.

Now `ddtrace` is updated to `0.49.0`. Awesome.

Now I need to update dependencies in a microservice that relies upon `pynternal`. Let's call it `pyblic`. I update to the latest version of `ddtrace` and `pynternal`. Oh no! There's a version mismatch. `0.48.3` is not compatible with `0.49.0`. Poetry correctly refuses to install.

Now I have to go update `pynternal` and run through it's release process for every minor version of `ddtrace`. This is not a happy solution.

See also https://github.com/DataDog/dd-trace-py/issues/762
While I don't agree that it's useless and not following semver (because we should not expect it to not break), it does point out the same type of challenges.

**Comment by brettlangdon** [comment]
@Gidgidonihah thanks for raising these concerns. We 100% agree with you. While we do everything we can to treat `0.x` as if it is `1.x` (not claiming we haven't made mistakes in the past), we also want to move the library to 1.0.0.

We have a tasks we are tracking/actively working on first before we make this version bump. Since it isn't clearly stated (or codified) we want to solidify what our public API actually is, and what is it we want to maintain under semver moving forward. Majority of the changes we intend to make before 1.0 are adding deprecation warnings around classes/functions/etc that we want to remove or make private.

**Comment by Gidgidonihah** [comment]
Great. Thanks for the response. Can I suggest using the milestone feature and tagging the issues that need to be closed to see a v1?

**Comment by Kyle-Verhoog** [comment]
@Gidgidonihah we're actively working on this now and the work can be tracked with the `v1.0` label as well as in #2663
