### ISSUE TITLE
Failure while trying to trace DB (SQLAlchemy) in Tornado app

### ISSUE THREAD

**Issue by Forever-Young** [DataDog/dd-trace-py#265]
Tracing is initialized as
`trace_engine(db.engine, tracer, service='abc')`

I get such error:
`File "/usr/local/lib/python3.5/dist-packages/ddtrace/contrib/sqlalchemy/engine.py", line 65, in _after_cur_exec
   span = self.tracer.current_span()
File "/usr/local/lib/python3.5/dist-packages/ddtrace/tracer.py", line 220, in current_span
  return self.get_call_context().get_current_span()`

This current DB hit is done outside any request, while initializing application (registers some classes metadata into DB).

Is there a way to specify context, or that part should check if `get_call_context()` is not None?

**Comment by palazzem** [comment]
Thank you @Forever-Young ! we're checking that one to see if the SQLAlchemy integration must be updated. We're doing some work on this integration during these days, introducing also the `patch()` method instead of the `trace_engine()` (ref: #261).

I'll keep you updated! Thanks for reporting your issue!

**Comment by brettlangdon** [comment]
@Forever-Young we have since fixed this specific exception from being raised since version `0.24.0`

I am going to close this card for now, if you still are experiencing issues please feel free to re-open the card.
