### ISSUE TITLE
Requests HTTP library, status of 'Not ready yet' monkey patch?

### ISSUE THREAD

**Issue by oliw** [DataDog/dd-trace-py#286]
I'm curious what the status of the monkey patch for `requests` on your roadmap is?

I set it to true just to check and not seeing anything in my Traces. I did see some warnings in my trace agent that was saying that the span for requests had no Service. 

https://github.com/DataDog/dd-trace-py/blob/5b684b643671d444b5ebf640fa61ca4e0fa0383e/ddtrace/monkey.py#L30

```
PATCH_MODULES = {
.....
    'requests': False,  # Not ready yet
....
}
```

**Comment by brettlangdon** [comment]
/me doesn't work at Datadog

@oliw it is definitely production ready, we have been using it for a few months now with no issues. It is just not patched by default when calling `patch_all` with no arguments.

The typical reason why you won't see any traces is because a "service" isn't defined for the spans created by the `requests` patching.

If you can check the logs for the trace agent you might see messages "Dropping trace no service was set". I don't remember exactly what the message says, but it is a pretty obvious message.

```
tail -f /var/log/datadog/trace-agent.log
```

Any spans that are created without a service defined (or whose parent spans do not have a service defined) will get ignored.

There are a few options to get around this:

```python
from ddtrace import tracer
import requests

# Wrap a function
@tracer.wrap(service='my-app'):
def make_http_call():
    res = requests.get('https://httpbin.org/status/200')

# Context manager
with tracer.trace('trace.name', service='my-app'):
    res = requests.get('https://httpbin.org/status/200')
```

I hope this helps point you in the right direction.

**Comment by oliw** [comment]
Thanks for sharing. I'm using it within the context of a Flask app. 

```
traced_app = TraceMiddleware(app, tracer, service="my-flask-app")
```

**Comment by brettlangdon** [comment]
Ah... then, not entirely sure... the `trace-agent.log` still might be able to give a little insight.

**Comment by palazzem** [comment]
Hello @oliw! the current state of the `requests` integration is that spans are properly created and collected, but no resources and services are defined. We're working on a specification for integrations that may have a high cardinality of elements (especially in a distributed system). Until then, you can define services by yourself like Brett wrote in a previous comment!

If it doesn't work, investigating on logs it's something that can help us to identify a possible bug with the integration. Thank you!

**Comment by oliw** [comment]
Hi, 

Thanks for the insight! Its working now, I think I was just looking at the wrong traces in DataDog to verify it was working as expected.

Thanks again

**Comment by palazzem** [comment]
No worries! Thank you @oliw!
