### ISSUE TITLE
Using start_span() and trace() in the same service

### ISSUE THREAD

**Issue by jbonzo** [DataDog/dd-trace-py#299]
I was wondering what the intended use was for each of these methods. I understand` trace()` uses context more so multiple traces that occur in a nesting fashion creates a lineage of spans, this makes sense. `start_span()` seems to be similar but puts more responsibility on the user to define the lineage via another span or some context. 

But my question lies in the mixing of the two __OR__ this particular case of two `start_span()` calls in a row (I'll get to that one second). 

The first case is when a user creates a root span by calling `start_span()` then `start_span(child_of=tracer.get_call_context()`. Here's an example:

```python
span  = tracer.start_span("name", "service", "resource")
different_span = tracer.start_span("different name", "service", "resource",
child_of=tracer.get_call_context())
```
My assumption is that `different_span` should be the child of `span`, but I don't believe this is the case. When `span` was created with the `child_of` arg being passed in as default `None`, the `start_span` does the following:

1. Creates its context variable
1. Creates a span with no specified parent, implicitly creating a root span
1. [Attempts to retrieve some `parent_span_id` and `parent_trace_id`](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/tracer.py#L166)
1. Adds the span to the context variable
1. Exits the method

At this point the tracer object's context looks the same as it did before `start_span` was called since the context which just gained a new span was garbage collected at the end of the method. I also notice that step 3 seems to take no effect seeing as that line is only executed if `parent` is None which means the `context` variable was newly created making `parent_span_id` and `parent_trace_id` default to `None`. This could be due to an intention of created a Context Provider that better supports distributed tracing and maybe these couple of lines are themselves a WIP. 

I'm just more curious on what the intention is in this case of using `start_span` seeing as if a span is created with `child_of=None` then its not only a root span but has little opportunity for it being a parent span as well.

This goes with using `start_span(...,child_of=None` and then `trace()` as well. I see a similar effect happening and wonder if the intention is to use `trace()` only with other `trace()`'s and `start_span()` mostly by passing in the parent span directly.

Apologies for the long post but this caused my great confusion when developing with the library and made me question my understanding of it.

**Comment by jbonzo** [comment]
So I just found that `context.add_span()` sets the span's context to itself, which helps me understand the point of creating the context variable there. But I don't see how that relates back to the tracer object that spun off the method to create the span. I'll keep looking

**Comment by palazzem** [comment]
Hello @jbonzo and thank you for reaching us! So let me explain our API, since we've changed it a bit in the last months and unfortunately the documentation may need a revamp. Our API is mainly composed by:
* `Tracer.trace()`: is our main API and the way to go when you need to instrument your framework, library or application (manual instrumentation). It uses our in-process context propagation to find the current active `Span`. In that way, you don't need to move your `Span` reference around the code to set the `child_of=` parameter. It will be automatically inherited from our propagation system.
* `Tracer.start_span()`: is the manual API that was here to mimic the same API from the [OpenTracing specification][1]. Because in some situations it's possible that the propagation system has troubles to find out the current active `Span` (think about complex applications with a lot of asynchronous calls like `asyncio` or Tornado), this API ignores all the above and allows you to easily define your hierarchy. It is intended to be used only to cover some edge cases and, indeed, it doesn't use the automatic in-process propagation.
* the `Context` class is our internal machinery to keep track of the current active `Span`, the current trace, and the current `parent_span_id` / `parent_trace_id` (this is recently added and yet not released). It's very uncommon to use that object directly and indeed it's not documented because no one should use that directly when creating their traces. It's created, handled and propagated by the above APIs.

About your example `start_span(child_of=tracer.get_call_context()`, it's actually working but what you're trying to achieve is already handled by the other API. Indeed,`Tracer.trace()` is the way to go and `Tracer.start_span()` is here only for specific edge cases where manual handling is required.

About `context.add_span()`, it's still part of our internal machinery and it should not be used directly (hence it's not documented in our examples). So to summarize:
* always use `Tracer.trace()` as a way to go since it uses in-process context propagation making everything easier
* in some edge cases you may use `Tracer.start_span()` to define your hierarchy, though it will not inherit any `Span` unless you specify that
* don't use the `Context` class directly, but let the library handle that

Hope it helps and feel free to ask more questions if you need!

[1]: https://github.com/opentracing/opentracing-python/blob/a86ee3d49df569691433e0ce0101105638ca8be8/opentracing/tracer.py#L44-L49

**Comment by jbonzo** [comment]
Follow up, I noticed that the `parent_span_id` and `parent_trace_id` were released in the new version. How are they intended to be set and used?

**Comment by palazzem** [comment]
@jbonzo yes at the moment both fields are part of a [WIP] API, hence they're not documented (and that's why the accessor is prefixed with underscore / "not public"). For the moment the fields and the `Context` itself are meant to be used only for internal machinery. As soon as the tracing API is stable and flexible enough, we'll provide the proper documentation to it.

Hope it helps and feel free to ask more questions about the topic!

**Comment by brettlangdon** [comment]
@jbonzo closing this issue as it appears to have been answered awhile ago. Please feel free to re-open if not, or open a new issue if you have any other questions!
