### ISSUE TITLE
Deprecate/internalize ddtrace.propagation module

### ISSUE THREAD

**Issue by ZStriker19** [DataDog/dd-trace-py#3066]
`ddtrace.propagation` makes it seem like we provide a propagation API but we only actually provide our own http implementation and it isn't configurable (a user cannot replace which propagator is being used). We want to deprecate `ddtrace.propgagtion.utils` but instead should we consider the future of the entire module?

Potential options for 1.0:

1. Internalize `ddtrace.propagation` since there isn't an API that is available to use anyway.

2. Replace `ddtrace.propagation` with a propagation API that users can use to roll their own propagation (this would involve changes to `tracer` or integrations)

3. Leave `ddtrace.propagation` for later and just deprecate ddtrace.propagation.utils for now.
Depending on what we choose we'll need to make an additional deprecation PR on master to reflect the upcoming deletion/movement of the methods.

**Comment by brettlangdon** [comment]
People are definitely using the existing propagation API, especially the `HTTPPropagator`.

We can probably defer the deprecation/removal until later. Since we can (likely) introduce a new/better API and keep the existing one around without too much hassle. Mostly since the existing API is just a wrapper around adding or extracting keys/values to a `dict`, there isn't any "magic" other than we use it in our integrations by default.

**Comment by Kyle-Verhoog** [comment]
> People are definitely using the existing propagation API, especially the HTTPPropagator.

So the only way a user can use the HTTPPropagator is to do something like in their application:

```python
ctx = HTTPPropagator.extract(headers)
if ctx.trace_id:
    tracer.context_provider.activate(ctx)
```

Which has few major caveats in my opinion:

- It needlessly exposes `Context` as an intermediate api (the user has no need for context otherwise when doing what they require here).
- If a trace is already active these operations will break the existing trace by creating a new trace and activating it. So two traces will be created.

> other than we use it in our integrations by default.

- There's actually no way for a user to override the propagator used in integrations. The "expected" solution for this is to disable distributed tracing in the integration, implement a propagator, cross fingers that at the point of extraction there isn't already a trace, extract and activate the trace.


The API is poor and I think it needs to change. However, our goal with 1.0 is reducing the public API to only what needs to be exposed. The question is whether `HTTPPropagator` needs to be exposed and the answer is that it's the only way to activate a distributed trace in the current API, which makes it necessary. Bottom line here is that I think we need to begrudgingly keep it for now and proceed just with (option 3) deprecating/internalizing `ddtrace.propagation.utils` so I agree with @brettlangdon.

It's tempting to use the opportunity of a breaking change to improve the API but it'll add to the overhead of upgrading.


## Addendum 

It is worth noting that work has been started on this front.

https://github.com/DataDog/dd-trace-py/pull/2406 proposes an API which adds propagator to tracer.

https://github.com/DataDog/dd-trace-py/pull/2888 proposes what this API could look like while also adding B3 support

**Comment by brettlangdon** [comment]
> But if they want to use one of the integrations, they would have to replace the HTTPPropagator in the ddtrace.propagation.http module. In 1.0, we could provide an API to do without messing with loaded modules, e.g. an argument to tracer.configure() for customizing the http propagator.

I was having a similar thought today about what the API/configuration could look like. Being able to globally configure a different propagator is interesting until you get to integration specific propagators, like what do we do for injecting context into a SQL query (for a crazy out there idea). Or, let's say you want to parse Datadog http headers, but inject B3. Or, let's say you want to use Datadog http headers internally, but B3 for one outbound connection.

**Comment by Kyle-Verhoog** [comment]
@ZStriker19 looks like we're in agreement to proceed with option 3. Let's keep the issue open and rename to covering the new API for propagators
