### ISSUE TITLE
requests.py autopatching

### ISSUE THREAD

**Issue by vagelim** [DataDog/dd-trace-py#318]
Ostensibly introduced in 0.4.0, the requests.py package is [still not autopatched](https://github.com/DataDog/dd-trace-py/commit/2cf9d8116c0c7781ef7971fa0af07c686b89d57a).

Is there a timeline or update on when the requests package will be patched when calling `patch_all()` without arguments?

**Comment by palazzem** [comment]
Hello @vagelim! at the moment we're not auto patching `requests` module with `patch_all()` because we haven't defined yet how to handle the default service name (and resource name) when the root span is a requests span. As soon as we finish our internal specification, I'll write you here more details.

Is currently an issue for you, or it's more a generic question about an ETA?

**Comment by vagelim** [comment]
Hi @palazzem, I'd say it's a bit of both a general question and an issue because we much prefer to add tracing to our applications with the fewest changes to our source as possible. Using the ddtrace-run wrapper is our most preferred way to add Datadog APM to our applications, but we can continue to manually patch for requests (and celery & boto) without issue.

**Comment by palazzem** [comment]
Oh, I see. The goal is having at some point all the instrumentation with fewer changes, but at the moment some frameworks / libraries are excluded because they need more configuration otherwise something will not work (mostly if used as a standalone and not together with other instrumentation).

I will keep you updated anyway. Thank you for reaching us!
