### ISSUE TITLE
Any chance of Django 1.3 support?

### ISSUE THREAD

**Issue by mattwilliamson** [DataDog/dd-trace-py#326]
I know it's old and unsupported, but it would save my team a whole lot of work if it would work out of the box. One example is no `setting_changed` signal.

**Comment by palazzem** [comment]
@mattwilliamson at the moment is not in our radar since we're following the Django support table to decide when add /drop support to a specific Django version. This is the current supported matrix: https://www.djangoproject.com/download/#supported-versions

For any other version that reached the end of extended support, we only offer best-effort support. So it really depends on how much work is to keep this unsupported version of Django. I'm closing the issue but feel free to re-open it if you have an idea if it's easy to support.

Thank you very much!
