### ISSUE TITLE
tracer.configure(enabled=False) prevents spans from being created

### ISSUE THREAD

**Issue by mcall52** [DataDog/dd-trace-py#3306]
### Which version of dd-trace-py are you using?
0.58.4

### Which version of pip are you using?
21.2.4 (installing dependencies through poetry 1.1.11 if that matters)

### Which version of the libraries are you using?

astroid                  2.9.3          
attrs                    21.4.0         
babel                    2.9.1          
bidict                   0.21.4         
black                    21.12b0        
cachecontrol             0.12.10        
cachetools               4.2.4          
certifi                  2021.10.8      
cfgv                     3.3.1          
charset-normalizer       2.0.10         
click                    7.1.2          
clickclick               20.10.2        
connexion                2.10.0         
datadog                  0.43.0         
ddtrace                  0.58.4         
dependency-injector      4.37.0         
deprecated               1.2.13         
distlib                  0.3.4          
dotenv-cli               2.2.0          
filelock                 3.4.2          
firebase-admin           5.2.0          
flask                    1.1.4          
flask-talisman           0.8.1          
google-api-core          2.4.0          
google-api-python-client 2.36.0         
google-auth              2.3.3          
google-auth-httplib2     0.1.0          
google-cloud-core        2.2.2          
google-cloud-firestore   2.3.4          
google-cloud-pubsub      2.9.0          
google-cloud-spanner     3.12.1         
google-cloud-storage     2.0.0          
google-crc32c            1.3.0          
google-resumable-media   2.1.0          
googleapis-common-protos 1.54.0         
grpc-google-iam-v1       0.12.3         
grpcio                   1.43.0         
grpcio-status            1.43.0         
gunicorn                 20.1.0         
httplib2                 0.20.2         
httpretty                1.0.5          
identify                 2.4.4          
idna                     3.3            
inflection               0.5.1          
iniconfig                1.1.1          
isodate                  0.6.1          
isort                    5.10.1         
itsdangerous             1.1.0          
jinja2                   2.11.3         
jsonpointer              2.2            
jsonschema               3.2.0          
lark-parser              0.11.3         
lazy-object-proxy        1.7.1          
libcst                   0.4.0          
markupsafe               2.0.1          
marshmallow              3.14.1         
mccabe                   0.6.1          
msgpack                  1.0.3          
mypy-extensions          0.4.3          
nodeenv                  1.6.0          
openapi-schema-validator 0.1.6          
openapi-spec-validator   0.3.2          
packaging                21.3           
pathspec                 0.9.0          
platformdirs             2.4.1          
pluggy                   1.0.0          
pre-commit               2.17.0         
proto-plus               1.19.8         
protobuf                 3.19.3         
py                       1.11.0         
pyasn1                   0.4.8          
pyasn1-modules           0.2.8          
pylint                   2.12.2         
pyparsing                3.0.6          
pyrsistent               0.16.1         
pytest                   6.2.5          
pytest-mock              3.6.1          
python-dateutil          2.8.2          
python-json-logger       2.0.2          
pytz                     2021.3         
pyyaml                   5.4.1          
redis                    4.1.2          
requests                 2.27.1         
rfc3339-validator        0.1.4          
rfc3986-validator        0.1.1          
rsa                      4.8            
six                      1.16.0         
sqlparse                 0.4.2          
swagger-ui-bundle        0.0.9          
tenacity                 8.0.1          
toml                     0.10.2         
tomli                    1.2.3          
typing-extensions        4.0.1          
typing-inspect           0.7.1          
uritemplate              4.1.1          
urllib3                  1.26.8         
virtualenv               20.13.0        
webcolors                1.11.1         
werkzeug                 1.0.1          
wrapt                    1.13.3  

### How can we reproduce your problem?

I don't have a minimal example but I can add what I am doing. I'm running a test suite that tests flask APIs and some internal functions as well. Since we don't want to see error messages for ddtrace when running unit tests we set `tracer.configure(enabled=False)` in the top-level conftest.py. Then we run our tests using pytest. An internal library that my company maintains has a function that is called during the test with the following statement `tracer.current_root_span().set_tag("some_tag", value)`. 

### What is the result that you get?

The test fails with 
```
>           tracer.current_root_span().set_tag(tag_key, value)
E           AttributeError: 'NoneType' object has no attribute 'set_tag'
```

### What is the result that you expected?

From the [docs](https://ddtrace.readthedocs.io/en/stable/advanced_usage.html#tracer) on the `configuration()` function, I expected a root span to still be created, just not uploaded to the ddtrace host. Specifically this statement:
```
enabled (bool) – If True, finished traces will be submitted to the API. Otherwise they’ll be dropped.
```
Now, obviously we should handle the case where `tracer.current_root_span()` returns `None` but it was not clear in the docs that a span would not be created if `tracer.configure(enabled=False)` is called. Is this expected behavior or a bug?

**Comment by brettlangdon** [comment]
Hey @mcall52 thanks for opening this issue.

Yes, since the return type of `Tracer.current_root_span()` is `Optional[Span]` we always recommend checking for `None`.

> Is this expected behavior or a bug?

For some integrations, yes this is expected. In order to improve performance of some integrations when the tracer is disabled we will avoid creating the spans.

This implementation detail is not consistent across all integrations, which I agree would cause some confusion.

**Comment by daniellehanks** [comment]
Wow, thanks for the lightning fast response. Is there any way to tell it to still create traces? We'd like to test all the ddtrace functionality we have in place, just not send it up since there is no host. As @mcall52 mentioned, the docs specifically say (emphasis mine):
>If True, **finished** traces will be submitted to the API. Otherwise they’ll be dropped.

To me, this implies that all traces/spans should still be created like normal.

**Comment by brettlangdon** [comment]
> To me, this implies that all traces/spans should still be created like normal.

We haven't really ever defined what the expected behavior should be. (not that we shouldn't, but sort of where we are now)


> Is there any way to tell it to still create traces? We'd like to test all the ddtrace functionality we have in place, just not send it up since there is no host.

Are you willing to share some more information about what you are trying to test?

E.g. you want to assert that a span exists, and you can call `set_tag()` on it? Or do you actually want to validate the data produced by the tracer?


Also, I know I am proposing a paid solution to your problem, but our [CI Visibility](https://www.datadoghq.com/product/ci-cd-monitoring/) product is really cool.

**Comment by daniellehanks** [comment]
@mcall52 explained our test setup. We have code that expects a span to exist and unconditionally calls `set_tag()`. We would like to not have to mock out ddtrace, as that has downsides (mocks can get out of sync with reality). We could add a None check in the main code to only `set_tag()` if the span exists, but that can mask real bugs (the violation of the caller not setting up a trace and then our tags are missing and no one is the wiser). Our function in question clearly states that it must be called within a trace context. So, in a way, our test breaking is a good thing as it's telling us there is no trace context. But that is only because the tracer was disabled. In summary, we want our test code as far as ddtrace is concerned to exercise normally as it would in production for high fidelity testing.

**Comment by daniellehanks** [comment]
I skimmed the CI Visibility link and it does look really cool, but even if we did want to set that up, we still need to be able to run tests locally outside of CI and not have it spew datadog connection errors.

**Comment by brettlangdon** [comment]
I don't love this suggestion since I am suggesting you to use an internal API, but you could always create a no-op trace writer to use.

This is the interface which needs to be implemented:
https://github.com/DataDog/dd-trace-py/blob/8fee243f2a23067a86326f425400f24ca0c78876/ddtrace/internal/writer.py#L155-L174

```python
import ddtrace
from ddtrace.internal.writer import TraceWriter


class NoopTraceWriter(TraceWriter):
    def recreate(self):
        # type: () -> TraceWriter
        pass

    def stop(self, timeout=None):
        # type: (Optional[float]) -> None
        pass

    def write(self, spans=None):
        # type: (Optional[List[Span]]) -> None
        pass

    def flush_queue(self):
        # type: () -> None
        pass


ddtrace.tracer.configure(writer=NoopTraceWriter())
```

We do something _kind of_ like this ourselves in our test suites. We have a writer which just collects all the traces produces so we can retrieve them later to make assertions on them.

If this approach/idea works, we can take it as a feature request.



And the other idea... you could just ignore those errors during CI runs.


(untested, but this should work)
```python
# conftest.py
import logging

ddtrace_writer_log = logging.getLogger("ddtrace.internal.writer")
ddtrace_writer_log.propagate = False
ddtrace_writer_log.setLevel(logging.CRITICAL)
```

**Comment by daniellehanks** [comment]
Thanks for the ideas, and including the code snippets.

Yeah, we generally very much dislike touching internal implementation details. It's brittle and asking to be broken on an otherwise innocuous dependency update, even on minor or patch versions since it's not part of the public API. That said, I did test your code snippet and it does work exactly as written dropped into our conftest. Would definitely like to see something like this implemented as this is the behavior we expected based on the current documentation, even if it's a separate argument or flag to set. I feel like the behavior may have changed with [this PR](https://github.com/DataDog/dd-trace-py/pull/2964), but cannot conclusively point to it as the same test is still broken on older versions.

Disabling the logging is a round about way to get at what we were after with disabling the tracer. It will cause it to still try to talk to the DD_HOST. While that really shouldn't matter much since we set that to a bogus value for tests, it does because we use httpretty to block and fail on any real network connection attempts (because unit tests should never be making real network tests, so blocking ensures that). It doesn't actually fail the tests, but presumably only because flush is called in a separate thread async. But it does whine very loudly about it in the output. And again, it is reaching into the internal namespace. Using the higher `ddtrace` namespace could mask other problems we should care about (say, deprecation warnings).

The pragmatist in me sees both suggestions as valid workarounds. However, the purist in me feels very icky wrt reaching into internal details, suppressing things that could mask real problems as a bandaid, allowing log cluttering by allowing the connection attempt through httpretty and relying on the implementation detail of async, etc.

Again, thanks for the quick responses @brettlangdon! Best and most timely support I've seen on an OSS repo in a long time and much appreciated!

**Comment by brettlangdon** [comment]
> I feel like the behavior may have changed with https://github.com/DataDog/dd-trace-py/pull/2964, but cannot conclusively point to it as the same test is still broken on older versions.

🤔 it shouldn't have. That PR fixed an issue where we were aggregating Spans in memory to be written, but then we never wrote them because we didn't call the appropriate "on finish" code. It _should_ have the same problem you are noticing today where `tracer.enabled = False` will produce some but not all of the Spans when `tracer.enabled = True`.

> Yeah, we generally very much dislike touching internal implementation details.

👍🏻 yeah, I didn't want you to have to do that forever. Since that approach seems to work for you we think it is a good idea to provide via our API. I have opened #3311 to add a `NoopTraceWriter` to the library.

**Comment by brettlangdon** [comment]
> It changed from unconditionally calling on_span_start to only calling it if enabled is True. I didn't dig beyond that, but that seemed conceptually possible to change from actually creating the spans and just not finishing them to not even creating the spans at all.

Ah, yeah. So `on_span_start` is just an event that allows us to trigger other behavior when a span is created. That won't impact the creation / context management of the Span itself.

We have a "SpanProcessor" which listens for these events and will aggregate created spans into a `dict[trace_id, list[Span]]`, then when a Span finishes it'll check to see if all the Spans for that trace are finished. If so, then it'll remove them from the `dict` and pass them off to the `AgentWriter`.

So that specific PR/bug was that when `tracer.enabled = False` we were calling `on_span_start` and continuing to aggregate Spans into this `dict`, but we never called `on_span_finish` so we would never actually try to remove them from memory, hence why it ended up in a leak.


> Thanks for getting that done so quickly! Hopefully it gets in a release soon.

As a heads up, it will take a minute to release. We are in the middle of working on `1.0.0` release, and we didn't want to increase the scope. So we are targeting `1.1.0`.

Some more context: one of the goals for our `1.0.0` release is to more clearly define our public API, and since that PR would increase our public API footprint we wanted to hold so we can give it some more thought / make sure we expose exactly what we need to.

**Comment by daniellehanks** [comment]
> As a heads up, it will take a minute to release. We are in the middle of working on `1.0.0` release, and we didn't want to increase the scope. So we are targeting `1.1.0`.

That's fine. My usual experience is that feature requests go into a black hole to never be seen again. So that fact that you had a PR open in a day is fantastic, even if we have to wait a bit for formal release.

> Some more context: one of the goals for our 1.0.0 release is to more clearly define our public API, and since that PR would increase our public API footprint we wanted to hold so we can give it some more thought / make sure we expose exactly what we need to.

My team is so happy that you guys finally (finally!) got around to promoting to v1. It's made dependency management painful since tooling treats patch versions on major version 0 as breaking. Love to hear that there is thought being put into exposed public API surface.

**Comment by brettlangdon** [comment]
@daniellehanks sorry for the very long delay here, but we finally got 1.0.0 released and decided to take a look at this issue and the POC PR #3311 

Introducing a `NoopTraceWriter` is definitely an elegant solution, but we are worried about the impact of making the writer interface public since it has been designed to be internal.

Another solution we have available that you can use is trace filtering.

https://ddtrace.readthedocs.io/en/v0.60.2/advanced_usage.html#trace-filtering

This API has been available for years.

A filter to drop all traces (create them, queue them, but don't encode or flush them) would look like:

```python
from ddtrace import Span, tracer
from ddtrace.filters import TraceFilter

class DropAllTracesFilter(TraceFilter):
    def process_trace(self, trace):
        # type: (List[Span]) -> Optional[List[Span]]
        return None  # Drop the trace

# And then configure it with
tracer.configure(settings={'FILTERS': [DropAllTracesFilter()]})
```


Do you think this solution could work for you? If this works for you we can look at adding this as a default filter available in the library.

**Comment by brettlangdon** [comment]
hey @daniellehanks I wanted to check in on this issue again to see if you've had a chance to review my latest suggestion for using trace filtering as a mitigation for the time being?

**Comment by daniellehanks** [comment]
Hi @brettlangdon, thanks for the thorough response. I no longer work for the same company, so don't have an easy way to try this out for you. @mcall52 does though and might be able to give it a spin.

**Comment by brettlangdon** [comment]
@mcall52 I am going to close this issue for now, please feel free to re-open if you are still having issues!
