### ISSUE TITLE
Handled exceptions from libraries with a datadog integration (e.g. boto3) get logged as an issue in APM Error Tracker

### ISSUE THREAD

**Issue by mcreenan** [DataDog/dd-trace-py#3733]
### Which version of dd-trace-py are you using?

0.27.0 (production)
1.1.12 (development/local)

### Which version of pip are you using?

21.2.4

### Which version of the libraries are you using?

boto3==1.14.63

### How can we reproduce your problem?

* Add ddtrace to a python project (in my case, this is a lambda function)
* Within the function
** Create a `cognito-idp` client via boto3
** Inside a try/except block, call the `admin_get_user` method on the client with a user pool that exists but a username that does _not_ exist

See code example:
```python
        try:
            return cognito_idp_client.admin_get_user(
                UserPoolId="<POOL ID THAT EXISTS>,
                Username="<USERNAME THAT DOES NOT EXIST>"
            )
        except Exception:
            pass
```

Note that this occurs for multiple, if not all, boto3 methods that throw an exception. For some methods, capturing the exception is the only option (e.g. cognito-idp.admin_get_user is the only way to lookup a user)

### What is the result that you get?

The trace gets logged in APM.

The exception, even though it's handled, gets logged in the APM error tracker.

Here's what it looks like in the error tracker:
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/118732/168324444-47886d5a-dc7a-4d8a-8de7-8005e1175b3c.png">

Then if you click into the issue and into a trace, this is what you see, showing the overall response was a successful status:
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/118732/168324822-dd0ae807-61ed-44bf-932c-4a8e7878ca44.png">

### What is the result that you expected?

Nothing logged in the APM error tracker.

**Comment by brettlangdon** [comment]
Hey @mcreenan thank you for reaching out.

The reason this happens is because when we create the span for the call to the AWS API we don't have visibility into the caller to know if they have caught the exception or not. So we attach it to the span. It is expected to show up in the flamegraph as an error, but the parent spans to not have an error indicating it was caught and handled.


However... we just introduced a new feature #3606 that allows you to specify for specific operations which response status codes are considered an exception.

The example we used in our docs is `s3.headobject` where a 404 generally isn't a bad thing, even though `botocore` does raise it as an exception.

Do you think this new feature would meet your needs?

If so, it is staged to go into `1.2.0` release (exact release date TBD).

**Comment by mcreenan** [comment]
> Hey @mcreenan thank you for reaching out.
> 
> The reason this happens is because when we create the span for the call to the AWS API we don't have visibility into the caller to know if they have caught the exception or not. So we attach it to the span. It is expected to show up in the flamegraph as an error, but the parent spans to not have an error indicating it was caught and handled.
> 
> However... we just introduced a new feature #3606 that allows you to specify for specific operations which response status codes are considered an exception.
> 
> The example we used in our docs is `s3.headobject` where a 404 generally isn't a bad thing, even though `botocore` does raise it as an exception.
> 
> Do you think this new feature would meet your needs?
> 
> If so, it is staged to go into `1.2.0` release (exact release date TBD).

Hey @brettlangdon , thanks for such a quick response.

That feature should be exactly what we need. Thanks, looking forward to testing it out!
