### ISSUE TITLE
SQLModel

### ISSUE THREAD

**Issue by fredrikaverpil** [DataDog/dd-trace-py#3904]
Hi! 👋 

I am interested in knowing how [SQLModel](https://sqlmodel.tiangolo.com/) would work (or not) with automatic tracing (when wrapping your app in `ddtrace-run`). Since it's using SQLAlchemy under the hood (which is [compatible](https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/python#datastore-compatibility) with ddtrace), I'm assuming queries done with SQLModel would be automatically picked up?

Am I right? 😄

**Comment by Kyle-Verhoog** [comment]
hey @fredrikaverpil!

If SQLModel is depending on and using SQLAlchemy under the hood then spans should be produced for the queries, yes.

It might be possible that SQLModel is using lower level elements in SQLAlchemy that might miss our instrumentation points. It looks like our SQLAlchemy integration simply wraps `create_engine` which it appears SQLModel doesn't use, so at a glance it looks like no data would be produced.

However, if the libraries are similar enough then reusing the patching for `create_engine` might work with SQLModel too. Feel free to try that and report back, otherwise we'd have to look at adding support for SQLModel. 🙂

**Comment by brettlangdon** [comment]
@fredrikaverpil per your request I'll close this issue, but please do report back in August!
