### ISSUE TITLE
Is it compatible with django 2.0?

### ISSUE THREAD

**Issue by Shemahmforash** [DataDog/dd-trace-py#397]

**Comment by mract** [comment]
+1

**Comment by palazzem** [comment]
Thanks for reporting that! One of our next steps is to update our compatibility list so that we know what we support and what not. In case we don't support something, we'll provide a proper fix.

**Comment by palazzem** [comment]
We have a community contribution to address one issue we're having with Django 2.0. Here the reference: https://github.com/DataDog/dd-trace-py/pull/415

Will update this issue once it has been merged. We can consider it a bug because without this change it's not going to work on all Django 2.0 applications. Thank you very much @Shemahmforash for reporting the issue!

**Comment by palazzem** [comment]
@Shemahmforash @mract the PR has been merged and I'm shipping a new release now. Will ping you again when it's out! Thank you very much for reporting the bug!

**Comment by Shemahmforash** [comment]
No problem. Thanks a lot for implementing the fix and merging it so quickly!

**Comment by si14** [comment]
Hey @palazzem, is there a chance the release can be pushed to pypi?

**Comment by palazzem** [comment]
@si14 sure thing! we spent the last week testing the package before the release. It will happen this week, I'll ping this thread again. Thank you very much and sorry for the wait.

**Comment by palazzem** [comment]
@si14 @Shemahmforash problem fixed with the latest release! https://github.com/DataDog/dd-trace-py/releases/tag/v0.11.0!

Thank you very much again!
