### ISSUE TITLE
Tortoise ORM support

### ISSUE THREAD

**Issue by hamza878** [DataDog/dd-trace-py#4072]
I'm working on a FastAPI project that uses tortoise ORM and i'm look to add ddtrace into it. Can you provide the integration for it? thanks!

**Comment by mabdinur** [comment]
Hey @hamza878, 

Thanks for bringing this to our attention. The APM Python team is always looking to support new libraries. We'll add this feature request to our backlog. Feel free to open a PR if this is an urgent request and I can help provide feedback.

**Comment by emmettbutler** [comment]
I'm closing this because of its old age. As @mabdinur mentioned, the request for a tortoise ORM integration is in our team's feature backlog and is not planned for the short term. As part of the backlog it will be considered during feature prioritization.

If anyone reading this is motivated to contribute the integration, please do so.
