### ISSUE TITLE
Add Celery task args and kwargs on celery.run span

### ISSUE THREAD

**Issue by ZacharyThomas** [DataDog/dd-trace-py#4225]
### Which version of dd-trace-py are you using?

1.4.x

### Which version of pip are you using?

22.2.2

### Which version of the libraries are you using?

celery = "==5.2.7"

### How can we reproduce your problem?

Run any Celery task

### What is the result that you get?

A span, but it could have more info :( 

### What is the result that you expected?

A span with task.arg and task.kwargs populated. Celery exposes task args in the postrun signal, so it should be pretty simple to enrich the span. This helps with debuggability in our Celery tasks. 

I believe just doing this is enough:
```
TAG_KEYS = frozenset(
    [
        ("args", "celery.task_args"),
        ("kwargs", "celery.task_kwargs"),
```

**Comment by Kyle-Verhoog** [comment]
hey @ZacharyThomas, thanks for writing this up!

So likely we won't be able to do args/kwargs because they can contain sensitive information.


Is the motivation for this change that manual instrumentation would be too cumbersome? You should be able to add a signal handler that attaches the data to the span:


```python
from celery.signals import task_postrun
from ddtrace import tracer

@task_postrun.connect
def instrument_task(sender, **kwargs):
    span = tracer.current_span()
    span.set_tag(...)
```

Note that the ddtrace instrumentation uses the postrun signal to finish the trace so it's important that this signal handler runs before the ddtrace handler (I don't recall if/how celery allows you to order signals)

Another possible solution is to write a decorator for your tasks that reports `*args, **kwargs` on the span.


Let me know what you think 🙂

**Comment by ZacharyThomas** [comment]
Hey @Kyle-Verhoog , I don't think there's a way to order the signals :(

I don't know if I could do something like:

```
patch(celery=False)
app = Celery()

@task_postrun.connect
def my_thing():
  do_stuff

patch(celery=True)
```

To force my signal handler to be first. 

>Another possible solution is to write a decorator for your tasks that reports *args, **kwargs on the span.

I see, I think I could hook into `task_before_start` and manually instrument as you suggested. I will give that a try. Thanks!

**Comment by ZacharyThomas** [comment]
Yep that worked - for posterity

```
class BaseTask(celery.Task):
    def before_start(self, task_id: str, args: tuple, kwargs: dict) -> None:
        try:
            span = tracer.current_span()
            if span:
                span.set_tag("celery.args", args)
                span.set_tag("celery.kwargs", kwargs)
        except Exception:
            pass
```
