### ISSUE TITLE
Is there a better way to trace async functions?

### ISSUE THREAD

**Issue by kglee0** [DataDog/dd-trace-py#4530]
### Summary of problem
Is there a way for me to see 

### Which version of dd-trace-py are you using?
1.6.0

### Which version of pip are you using?
22.1.2

### Which libraries and their versions are you using?
fastapi == 0.85.2
asyncpg == 0.26.0
SQLAlchemy == 1.4.43

### How can we reproduce your problem?
By tracing async frameworks.

### What is the result that you get?
Different duration for the same async call
e.g.
- Request A: `await some_db.connect()` records a duration of 1ms
- Request B: `await some_db.connect()` records a duration of 100ms

### What is the result that you expected?
Somewhat similar duration for the same async call. From what i understand, because FastAPI is asynchronous, there is no guarantee when the event loop would run the exact coroutine.
However, currently the flamegraph and the duration of the span looks as if the call itself took the entirety of the duration. Is there a way to better trace this kind of async execution?

Below, they're the same calls (BEGIN) to the database, but one took 2ms while the other took 53ms. I assume calling 'begin' to the database is cheap operation, but due to the asynchronous nature, one took 53ms to finish, which could cause confusion if i want to know how my queries are doing.

<img width="484" alt="스크린샷 2022-11-11 오후 4 00 39" src="https://user-images.githubusercontent.com/107823706/201283966-94b8cd80-a5fe-475c-955d-aa7c86f1aa67.png">
<img width="429" alt="스크린샷 2022-11-11 오후 4 02 32" src="https://user-images.githubusercontent.com/107823706/201283950-316cabed-50f4-4ad2-abd0-97b1973ac214.png">

**Comment by Kyle-Verhoog** [comment]
hey @kglee0, thanks for reaching out!

Indeed tracing async operations can be tricky. Are you asking about getting more insight into why a particular operation may take longer (due to async scheduling, blocking, etc)?

If so, this isn't supporting today by the tracing product and is quite tricky to accomplish in general with tracing. We'd need to instrument the event loop which can be very noisy and generate massive amounts of data.

Our [profiling product](https://www.datadoghq.com/product/code-profiling/) is a good way to get more insight about where time in your application is being spent.

**Comment by kglee0** [comment]
Thanks for the reply @Kyle-Verhoog! I'll have a look at profiling :) Have a nice day!
