### ISSUE TITLE
Change format for DD_SERVICE_MAPPING option

### ISSUE THREAD

**Issue by StasEvseev** [DataDog/dd-trace-py#5101]
### Summary of problem
I kind of like that there is a way to map one APM service to another using `DD_SERVICE_MAPPING`. But there is one drawback of format which has been chosen `original_service:mapped_service`. If we are to have `original_service` contains `:` in the name, then mapping looks like `mysql:80:python-mysql` and I believe it is not parseable by `ddtrace`. Tested it with `parse_tags_str`.

Do you think changing separator from `:` to some other symbol(which can't be part of APM service name) would be appropriate change? 

### Which version of dd-trace-py are you using?
1.7.3

<details>
  <summary>`pip freeze`</summary>
  
</details>

### How can we reproduce your problem?
```
from ddtrace.internal.utils.formats import parse_tags_str

parse_tags_str("mysql:80:python-mysql") # result: {"mysql:80": "python-mysql"}

# or change separator to other symbol 

parse_tags_str("mysql:80=>python-mysql") # result: {"mysql:80": "python-mysql"}

```

**Comment by ZStriker19** [comment]
Hi @StasEvseev, thanks for opening the issue, we'll review as a team.

**Comment by StasEvseev** [comment]
@ZStriker19 any news on this one?

**Comment by emmettbutler** [comment]
@StasEvseev because `DD_SERVICE_MAPPING` is implemented in or requested on multiple Datadog tracing libraries (example https://github.com/DataDog/dd-trace-rb/issues/2386), we need to do some coordination to ensure the interface remains consistent. Since that effort is beyond the scope of dd-trace-py, I'm going to close this ticket in favor of one in our internal backlog that tracks the cross-tracer coordination effort. It'll be prioritized alongside other feature requests in an upcoming planning pass. Thanks for the contribution, by the way!
