### ISSUE TITLE
Allow service names to be set in patch call

### ISSUE THREAD

**Issue by goodspark** [DataDog/dd-trace-py#547]
I have a web app that touches a lot of services, from mysql, redis, memcached, boto, etc.

I also work in a company that has at least one other team using Datadog APM. They've setup their Datadog tracer agent to prefix their services with their project (eg. `myproject-mysql`). This is nice because then services are namespaced, don't collide with other projects' usages, and declutter/organize the [DD APM view](https://app.datadoghq.com/apm/services).

However, the experience to do this with the Python client could be improved.

Right now:

```python
from ddtrace import patch
from ddtrace import Pin
from redis import StrictRedis

patch(redis=True)

Pin(service='myproject-prod-redis', app='redis', app_type='db').onto(StrictRedis)
```

Having to import specific modules/objects/classes for each service just to set the service name feels really messy. So I either have to add this code to all the main points where I import various services and clients _or_ do this all in my init module(s).

What I would like:

```python
from ddtrace import patch_module

MY_SERVICE_PREFIX = 'myproject-prod-'
MY_SERVICE_LIST = ['redis', 'mysql', 'memcached', 'boto']

for service in MY_SERVICE_LIST:
  patch_module(
    service,
    name='{}-{}'.format(MY_SERVICE_PREFIX, service),
  )
```

Or, if done through the config API (like how @Kyle-Verhoog mentioned is done for celery):

```python
from ddtrace import config
from ddtrace import patch_module

MY_SERVICE_PREFIX = 'myproject-prod-'
MY_SERVICE_LIST = ['redis', 'mysql', 'memcached', 'boto']

for service in MY_SERVICE_LIST:
  patch_module(service)
  config[service]['service_name'] = '{}-{}'.format(MY_SERVICE_PREFIX, service)
```

**Comment by Kyle-Verhoog** [comment]
Hi @goodspark!

We agree. Our convention of configuration is not ideal. We already have an alternative approach which we have used for our `celery` integration. Usage looks something like this:

```python
from ddtrace import config

config.celery['producer_service_name'] = 'task-queue'
config.celery['worker_service_name'] = 'worker-notify'
```

We are looking to switch over each of our integrations to use this style of configuration in the near future.

Although your proposed method of including the configuration when patching is intriguing. I like the idea of keeping all `ddtrace` related configuration bundled up together in one place. We could perhaps offer this functionality, which under-the-hood would use the `config` api.

Thanks for bringing this up!

**Comment by goodspark** [comment]
Slight update: After looking at the code I realize `patch` is the wrong place. Maybe in `patch_module`. But if I can do it through the config api, I'd be happy too. The core ask is to be able to do it in a single place without having to import a bunch of modules to manually pin things.

**Comment by goodspark** [comment]
@Kyle-Verhoog Would something like this work? https://github.com/DataDog/dd-trace-py/pull/549

**Comment by eedwards-sk** [comment]
Hi, I'd like to add that I've opened multiple support requests and issues with Datadog for more or less the same reason.

Right now most auto-instrumented services end up under the same namespace (even though we're specifying a service name at a parent level) so it makes for an overall awful user experience that keeps our devs from wanting to use APM.

Pin is not a solution for us because it requires too much manual configuration in the code and as @goodspark said it's ridiculous to have to import just to configure. 

Config API is an option but it still feels clunky because my environments are a result of where the code is launched, not the code itself, so I prefer setting these from environment variables and leaving the code agnostic.

Ideally, setting a 'service name prefix' at a parent level when using `ddtrace-run` would prefix ALL instrumented services that would show up in the service list to have that prefix, and immediately all my use cases would be solved.

**Comment by goodspark** [comment]
Hi all!

I've been looking at our DD APM integration again recently and I think I was wrong about all this!

I think what I'd prefer now is services to be named according to the actual resource they're for.

Ex: Lets say my service makes 3 calls to different AWS lambda functions. Right now I see:
![screenshot from 2019-02-09 11-44-32](https://user-images.githubusercontent.com/29210237/52525553-2f168b80-2c60-11e9-9bb2-dc1e817da9f7.png)

So I have no idea which lambda function is being called at this level. I'd have to open an actual trace to see what the function name was. That's very suboptimal and doesn't present a useful aggregation of information. Ex: What if only one of them regresses and has a performance problem? It'll be hard to quickly see that.

The same would apply to other services: Ex: DB, memcached, SQS, and even stuff like the requests Python library (name/group by API hostname).

FWIW, here's how NewRelic does it:
![screenshot from 2019-02-09 11-51-17](https://user-images.githubusercontent.com/29210237/52525615-135fb500-2c61-11e9-95e6-f1c595cb8cc7.png)

You see a break out for bitly.com. Not grouped into "external API calls" or "requests". I think NR could also be more specific with the lambda function here, but it's an improvement over Datadog's current approach.

The main benefit is simplifying and speeding up the drill down process in DD APM. Thoughts?

**Comment by brettlangdon** [comment]
hey @goodspark I think this does make sense, but I am going to close this issue for now, however if you would be willing to open new issues for each integration you'd like to see a change in, we can track the progress/requests better.

**Comment by eedwards-sk** [comment]
@brettlangdon that is a very confusing reason to "close" this issue. Where is the replacement issue that we can track this in? Are you really suggesting we open individual issues for each integration, even though this very issue is complaining of having to configure specific integrations? As I said earlier, and is still true today, I've continued to be frustrated with DD APM for this reason, we cannot set a parent level service and this makes the UX very poor.

This issue seems to sum up the problem well. So what is the benefit of closing it and putting the work on us to re-open the same problem? Are you merely improving your "open issue" metrics?

Pardon the frustration, but we've been paying for DD APM for a while now and you've continued to ignore and now close issues relevant to us without any real progress.

**Comment by brettlangdon** [comment]
@eedwards-sk sorry for any frustration with this issue, the reason I suggested individual issues is because we have addressed this problem for some integrations already, and so would like to be able to triage and track them separately.

**Comment by eedwards-sk** [comment]
@brettlangdon so what is the correct unified way of setting the prefix for every service that gets auto-instrumented by `ddtrace-run` so I can start testing it and open issues on services that aren't working?

**Comment by brettlangdon** [comment]
There currently is no way to set a service name prefix.

This original issue was referring to breaking out resource names based on db, url, AWS API call, etc. For some integrations we have added a way to "split" the resource name based on this information, but not the service name.

**Comment by eedwards-sk** [comment]
That's not what the original issue was for. Maybe you're thinking of the [follow-up comment they added](https://github.com/DataDog/dd-trace-py/issues/547#issuecomment-462074146)?

The [original issue](https://github.com/DataDog/dd-trace-py/issues/547#issue-355345419) is about being able to configure "for services foo, bar, baz, register them as my-prefix-foo, my-prefix-bar, my-prefix-baz"

My [above comment](https://github.com/DataDog/dd-trace-py/issues/547#issuecomment-444219035) describes the issue that still exists, which is wanting to configure this at an environment level, to support `ddtrace-run`.

It'd be nice if at the very least you had opened a new issue to persist this concern.

Otherwise it feels like I'm having to keep asking over and over again about this. I even engaged DD directly to ask them about design advice because the service UX is so bad in APM, that I figured I must be doing it wrong. I found no helpful advice, because APM is just a product datadog bought and then wedged into their ecosystem, and nobody I talked to had any real experience with it.

Why even have auto-instrumentation if the UX isn't optimized for real production systems? It'd be like buying a tesla with autopilot, but you can't turn it on outside of your garage.

**Comment by brettlangdon** [comment]
You are correct, I did mostly focus on the last comment of this issue.

We are in the process of doing some much needed issue grooming and I was maybe a little too hasty with closing this issue.

I have opened #1044 to specifically track the feature request to add a service name prefix.
