### ISSUE TITLE
ddtrace 1.13.0 changes name of internal logger used for ignoring

### ISSUE THREAD

**Issue by ArcLightSlavik** [DataDog/dd-trace-py#5859]
### Summary of problem
I am using sentry and previously we had a lot of internal error messages from datadog which we wanted to discard (see here https://github.com/DataDog/dd-trace-py/issues/5533). But updating from 1.12.3 to 1.13.0 changes the name of the internal logger from `ddtrace.internal.writer` to `ddtrace.internal.writer.writer`. These changes were made in this MR https://github.com/DataDog/dd-trace-py/pull/5531.

Question: are these changes intentional? I understand that it's the name of the internal logger but the looks of the MR this is unexpected. 

Question 2: maybe you can advice on a better value to ignore these errors? I assumed logger value would be better then just name of the error

### Which version of dd-trace-py are you using?
1.13.0

### Which version of pip are you using?
-

**Comment by mabdinur** [comment]
Hey @ArcLightSlavik,

Those changes were intentional. The name of the logger should match the name of the module. The `writer.py` module was refactored in an internal package, so this change is inline with our [version policy](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces).

There is no perfect solution here since the format of the logs and the name/path of the module can change at any point. For now I would recommend ignoring logs generated from `ddtrace.internal.writer.writer`. I don't think this file will be renamed anytime soon.  You can also add additional checks to filter ddtrace logs by file name and message but again there is no guarantee this won't break again. 

Sorry about the trouble 😞

**Comment by ArcLightSlavik** [comment]
👍 I changed the ignorer to cover anything in `ddtrace.internal`, hope that won't change soon 😁
