### ISSUE TITLE
ReadTheDocs Integration page missing config options

### ISSUE THREAD

**Issue by JBSK8NC** [DataDog/dd-trace-py#6897]
### Summary of problem
DDTrace readthedocs, Integrations page. The configuration keys are missing.
I had to go look them up for django [here](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/contrib/django/__init__.py)
Not sure if its a Sphinx issue.

### How can we reproduce your problem?
[integrations](https://ddtrace.readthedocs.io/en/stable/integrations.html)

### What is the result that you get?
<img width="805" alt="Screenshot 2023-09-12 at 10 09 29 PM" src="https://github.com/DataDog/dd-trace-py/assets/10166403/91d9c950-7976-465d-9b95-f413f453abc5">
<img width="252" alt="Screenshot 2023-09-12 at 10 09 54 PM" src="https://github.com/DataDog/dd-trace-py/assets/10166403/73d1e6b3-286a-488b-8bec-f9aab493fd36">

### What is the result that you expected?
I would like to see the config options in the doc's.

**Comment by mabdinur** [comment]
The docs for the django integration have not changed since ddtrace v1.7.0 ([last released update](https://github.com/DataDog/dd-trace-py/commit/7944751fd3e905b746079c46b57a6dcba602f2e4). The docs for v1.17.2 have the correct formatting and should be up to date:  https://ddtrace.readthedocs.io/en/v1.7.2/integrations.html#django

This issue should be resolved by v1.18.7 ([fix](https://github.com/DataDog/dd-trace-py/commit/a1af2274a905ccc323ba44b71ed13802182cb8c7)). We will try get this release out by the start of next week. Sorry for the inconvenience.
