### ISSUE TITLE
New psycopg update causes issues with ssl=require

### ISSUE THREAD

**Issue by ollz272** [DataDog/dd-trace-py#7079]
### Summary of problem
Since upgrading to psycopg 3.1.11 (and 12) we're getting the following issue with dd-trace:
```
  File "/Users/oliver/Library/Caches/pypoetry/virtualenvs/sherlock-9z3yAd_C-py3.11/lib/python3.11/site-packages/ddtrace/contrib/psycopg/async_connection.py", line 64, in patched_connect_async
    return patch_conn(conn, pin=pin, traced_conn_cls=traced_conn_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oliver/Library/Caches/pypoetry/virtualenvs/sherlock-9z3yAd_C-py3.11/lib/python3.11/site-packages/ddtrace/contrib/psycopg/connection.py", line 71, in patch_conn
    dsn = sql.parse_pg_dsn(conn.info.dsn)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.ProgrammingError: invalid dsn: invalid connection option "sslcertmode"
```

### Which version of dd-trace-py are you using?
1.20.2

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  aiodns==3.0.0
aiohttp==3.8.5
aiosignal==1.3.1
annotated-types==0.5.0
async-timeout==4.0.2
attrs==23.1.0
black==23.9.1
boltons==23.0.0
Brotli==1.0.9
bytecode==0.14.2
cattrs==23.1.2
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
coverage==7.2.6
ddsketch==2.0.4
ddtrace==1.20.2
Deprecated==1.2.14
envier==0.4.0
face==20.1.1
factory-boy==3.2.1
Faker==18.13.0
fire==0.5.0
frozenlist==1.3.3
GeoAlchemy2==0.14.1
glom==23.3.0
idna==3.4
importlib-metadata==6.0.1
iniconfig==2.0.0
more-itertools==10.1.0
multidict==6.0.4
mypy==1.5.1
mypy-extensions==1.0.0
opentelemetry-api==1.18.0
packaging==23.1
pathspec==0.11.1
pendulum==2.1.2
platformdirs==3.5.1
pluggy==1.0.0
protobuf==4.23.4
psycopg==3.1.12
psycopg-binary==3.1.12
psycopg-pool==3.1.7
psycopg2-binary==2.9.6
pycares==4.3.0
pycparser==2.21
pydantic==2.4.1
pydantic-settings==2.0.3
pydantic_core==2.10.1
pytest==7.4.2
pytest-asyncio==0.21.1
pytest-cov==4.1.0
pytest-docker==2.0.1
pytest-randomly==3.15.0
python-dateutil==2.8.2
python-dotenv==1.0.0
pytz==2023.3
pytzdata==2020.1
PyYAML==6.0.1
ruff==0.0.291
-e git+ssh://git@bitbucket.org/grodedge/sherlock.git@57883f52328e43852c813961dcdd8c08baecaabc#egg=sherlock
six==1.16.0
SQLAlchemy==1.4.48
SQLAlchemy-Utils==0.41.1
termcolor==2.3.0
time-machine==2.13.0
timescale_models==5.0.0
typing_extensions==4.7.1
wrapt==1.15.0
xmltodict==0.13.0
yarl==1.9.2
zipp==3.16.0
</details>

**Comment by ollz272** [comment]
As a further update, it seems that this was introduced as an option in libpq16, which it would seem ddtrace doesn't support. Please add support for this 🙏🏻 
https://github.com/psycopg/psycopg/issues/650#issuecomment-1738520604

**Comment by dvarrazzo** [comment]
For more info: the `sslcertmode` requires either psycopg2 non-binary and libpq 16 installed on the client, or psycopg2-binary 2.9.8 (just released), which bundles libpq 16.

**Comment by emmettbutler** [comment]
Thank you for the issue report! We'll add it to our backlog.

**Comment by emmettbutler** [comment]
@ollz272 I looked into this today, and my theory is that the trigger of the crash you're experiencing is actually the use of an outdated version of `psycopg2-binary`.

ddtrace's dsn-parsing logic is [imported directly from psycopg2-binary](https://github.com/DataDog/dd-trace-py/blob/45dba3c41b85962e6432fe87067fb9a1c2637f17/ddtrace/ext/sql.py#L56-L58), thus the `invalid dsn` error originates from psycopg2-binary. In my local tests, passing `sslcertmode` through `psycopg2.connect` succeeds under `psycopg2-binary==2.9.8` and fails under `psycopg2-binary==2.9.6`. This makes sense, because `sslcertmode` was added in 2.9.8. The inclusion or exclusion of ddtrace in the reproduction test does not affect this outcome.

I notice that your `pip freeze` output includes `psycopg2-binary==2.9.6`, and I suspect upgrading that requirement to 2.9.8 would solve your problem. Please give that a shot if you want, and comment here with the results.

I'm going to close this for the moment because I'm confident in this workaround and that there's no change necessary to ddtrace for this issue. Please let me know if you disagree and I'll reopen. Cheers!
