### ISSUE TITLE
Do you need DD_KEY even if we are using the Datadog Cluster Agent?

### ISSUE THREAD

**Issue by ryanpeach** [DataDog/dd-trace-py#7313]
https://github.com/DataDog/dd-trace-py/blob/8e68cfa4c00abcca35fb481788ac855c7c7f83fd/ddtrace/contrib/langchain/patch.py#L752

I was under the impression you just set the `DD_AGENT_HOST` and `DD_AGENT_PORT` environment varibles.

**Comment by mabdinur** [comment]
Out of the box the openai integration is not compatible with the Datadog Cluster Agent. To use this integration your application must be set the DD_API_KEY. This integration can be disabled by setting `DD_TRACE_LANGCHAIN_ENABLED=False`.

### Context

The ``DD_API_KEY`` environment variable must be set on a host to enable the openai integration. This is because the openai integration [sends logs directly](https://github.com/DataDog/dd-trace-py/blob/98aeeffeb7514c7acb88d53ff7e83a2770b5b552/ddtrace/contrib/_trace_utils_llm.py#L33) to datadog internal services (these logs are not forwarded by the agent).

**Comment by Yun-Kim** [comment]
Just to add, `DD_API_KEY` is only required if you wish to also enable the prompt/completion log sample feature. If you wish to continue using the langchain/openai integrations but do not set the required `DD_API_KEY`, I would suggest setting `DD_LANGCHAIN_LOGS_ENABLED` and `DD_OPENAI_LOGS_ENABLED` to `False`.
