### ISSUE TITLE
ddtrace 2.1.x causes test to hang that uses click and freezegun

### ISSUE THREAD

**Issue by fredrikaverpil** [DataDog/dd-trace-py#7385]
### Summary of problem

A test that runs fine in ddtrace-py 2.0.5 hangs forever with 2.1.0 (and any 2.1.x version).

### Which version of dd-trace-py are you using?

- 2.0.5: everything ok
- 2.1.0: hangs
- 2.1.3: hangs

### Which version of pip are you using?

N/A

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  freezegun==1.2.2
  click==8.1.7
  pytest==7.4.2
  ddtrace==2.1.3
</details>

### How can we reproduce your problem?

```python
# test_hang.py

from click.testing import CliRunner
from freezegun import freeze_time
from clickfile import hang

def test_hang():
    frozen_time = datetime(year=2022, month=1, day=1, hour=13, minute=37)
    with freeze_time(frozen_time):
        CliRunner().invoke(hang)
```

```python
# clickfile.py

import click
from ddtrace import tracer

@click.group()
def cli():
    pass

@cli.command()
@tracer.wrap(service="foo", resource="bar")
def hang():
    pass
```

### What is the result that you get?

The command `pytest -k test_hang` hangs forever on ddtrace 2.1.x but runs fine on 2.0.x.

### What is the result that you expected?

No hanging.

**Comment by ZStriker19** [comment]
Ran a git bisect and it looks like [ 4cb41f02958c845a24302fa9172d39ecf645777d ](https://github.com/DataDog/dd-trace-py/commit/4cb41f02958c845a24302fa9172d39ecf645777d) is at fault here. Probably because of our use of multiprocessing: https://github.com/DataDog/dd-trace-py/commit/4cb41f02958c845a24302fa9172d39ecf645777d#diff-b79457a3006017376c6ffaaeb34f3ffafa4f7f12e8f28dc96307faa196fd3e58R182

Its parent 518365cb1  is that last good commit.

It doesn't seem that CliRunner likes threads very much:
https://github.com/pallets/click/blob/ca5e1c3d75e95cbc70fa6ed51ef263592e9ac0d0/src/click/testing.py#L161-L178 

However multiprocessing should be using subprocesses instead of threads here.  It does mention "without any concurrency" though which subprocesses would cover, so that's probably the issue. 

We'll look into fixing this.

**Comment by emmettbutler** [comment]
@fredrikaverpil I've found that running your test command with an added environment variable set fixes this issue:

```
DD_REMOTE_CONFIGURATION_ENABLED=0 pytest -k test_hang
```

I dug deeply into this and haven't yet been able to pinpoint the specific thing that Click is doing that makes it not work with `multiprocessing.Queue.get()`. Given that, I think the best option at the moment is to apply this environment variable as a workaround. Does that work for you?

Thanks again for the contribution.
