### ISSUE TITLE
failed_to_send services to Agent: HTTP error status 400, reason Bad Request

### ISSUE THREAD

**Issue by Natim** [DataDog/dd-trace-py#757]
![image](https://user-images.githubusercontent.com/229453/49427174-f27f6d00-f7a2-11e8-9321-2caacc228eb9.png)

I am using ddtrace==0.17

**Comment by Natim** [comment]
Fallbacking to 0.16 seems to fix the issue.

**Comment by Kyle-Verhoog** [comment]
Hey @Natim! This is a known issue that will be resolved with the 0.17.1 release which will be released shortly. It has to do with the services endpoint which is now deprecated.

Thanks for the report. 😄

**Comment by Natim** [comment]
Thanks for the heads'up

**Comment by eedwards-sk** [comment]
I'm getting this on 0.16.0 as well. ETA? What is 'shortly' exactly? Thanks

**Comment by brettlangdon** [comment]
`0.17.1` should be released before the end of the week.

This error message, while annoying, should not have any impact on your application code or in traces being reported. If this is not the case, please let us know!

**Comment by Natim** [comment]
Well it does have an impact on the number of sentry we get :joy: but yes we can probably mute the paging there.

**Comment by brettlangdon** [comment]
@Natim :( I am sorry.

We are prepping the `0.17.1` release right now, if you were interested you could install the pre-release branch to test. `pip install git+https://github.com/datadog/dd-trace-py@0.17.1-dev`

But I will update here when the release is published.

**Comment by Natim** [comment]
Yeah no worries I was joking around, I fallback on 0.16 and everything is fine on my side, I will wait for the release of 0.17.1, thank you for your updates, we really appreciate them.

**Comment by Kyle-Verhoog** [comment]
Hey all!

0.17.1 is now out, the service sending should be no-op'd so no more 400s 😄.

Going to close this out, feel free to re-open if anything comes up.

**Comment by ewjoachim** [comment]
For anyone stumbling upon this:

> This error message, while annoying, should not have any impact on your application code or in traces being reported. If this is not the case, please let us know!

Actually, our Python Celery processes are launched by supervisor with
```bash
$VENV/bin/ddtrace-run $VENV/celery worker --pidfile=/tmp/%(program_name)s_%(process_num)s.pid
```

(I simplified a bit)

On ddtrace==0.17.0, our workers boot somewhere around 15% of the time succesfully, the rest of the time (85%), they hang forever before creating their pidfile (so I'd guess they're in ddtrace-run and not in celery yet), and strace says they're blocked by a futex. I've spent 30min restarting every process one by one until they manage to start up properly and leave futex hell. They're seen as healthy by supervisor because the process doesn't terminate.

On ddtrace==0.17.1, all the workers boot succesfully on the first try.
