### ISSUE TITLE
ddtrace can't patch a typed pymongo.MongoClient

### ISSUE THREAD

**Issue by iherasymenko** [DataDog/dd-trace-py#7681]
### Summary of problem

Patching a typed `pymongo.MongoClient` fails with an error.

https://pymongo.readthedocs.io/en/stable/examples/type_hints.html#basic-usage
### Which version of dd-trace-py are you using?
`2.2.0`
### Which version of pip are you using?
`23.3.1`
### Which libraries and their versions are you using?
```
attrs==23.1.0
bytecode==0.15.1
cattrs==23.2.1
ddsketch==2.0.4
ddtrace==2.2.0
Deprecated==1.2.14
dnspython==2.4.2
envier==0.4.0
importlib-metadata==6.8.0
opentelemetry-api==1.21.0
protobuf==4.25.1
pymongo==4.6.0
six==1.16.0
typing_extensions==4.8.0
wrapt==1.16.0
xmltodict==0.13.0
zipp==3.17.0
```
### How can we reproduce your problem?
1. Install `pip install pymongo==4.6.0 ddtrace==2.2.0`. MongoDB should not be required for this reproducer as the error happens before the connection is being established.

2. Create `typed_client.py`:
```
from typing import Any

import pymongo
from pymongo.database import Database

db_client: pymongo.MongoClient[dict[str, Any]] = pymongo.MongoClient(
    host="mongodb://localhost:27017/dummydb",
    connect=False,
)
db: Database[dict[str, Any]] = db_client.get_default_database()
```

3. Create `untyped_client.py`:
```
import pymongo
from pymongo.database import Database

db_client: pymongo.MongoClient = pymongo.MongoClient(
    host="mongodb://localhost:27017/dummydb",
    connect=False,
)
db: Database = db_client.get_default_database()
```

4. Run `ddtrace-run python typed_client.py` and observe the error.
5. Run `ddtrace-run python untyped_client.py` and observe no errors.
### What is the result that you get?
```
(venv) *** % ddtrace-run python typed_client.py              
Traceback (most recent call last):
  File "***/typed_client.py", line 6, in <module>
    db_client: pymongo.MongoClient[dict[str, Any]] = pymongo.MongoClient(
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: type 'TracedMongoClient' is not subscriptable
```
### What is the result that you expected?

Patching succeeds without any errors.

**Comment by mabdinur** [comment]
Hey @iherasymenko,

Thanks for bringing this to our attention.

The issue here is that the [MongoClient](https://github.com/mongodb/mongo-python-driver/blob/master/pymongo/mongo_client.py#L140) is a subclass of [DocumentType](https://github.com/mongodb/mongo-python-driver/blob/master/bson/typings.py#L29) which is a map/dictionary.

When ddtrace patches pymongo it [wraps](https://github.com/DataDog/dd-trace-py/blob/e180300a0e60ded2ea54576cf20fb663b3153815/ddtrace/contrib/mongoengine/trace.py#L31) the original MongoClient with a [TracedMongoClient](https://github.com/DataDog/dd-trace-py/blob/2757aaefc7f0121e581b3a480dbddf3937e2f024/ddtrace/contrib/pymongo/client.py#L49). This TracedMongoClient is not a map so it can't be typed in the same way.

To resolve this issue we will need to revisit our strategy for tracing pymongo clients. This might take some time. Will this issue prevent you from using the pymongo integration in the meantime?

**Comment by iherasymenko** [comment]
Thank you for looking into this @mabdinur . My team is trying to adopt types wherever possible and while this particular issue is not a blocker, it would be definitely great to have the `MongoClient` typed.

**Comment by emmettbutler** [comment]
We've added this issue to our internal backlog, and as such it will be prioritized in an upcoming planning round. Please reopen or comment if you think this issue was closed in error. Thanks!
