### ISSUE TITLE
INFO logs are getting lost

### ISSUE THREAD

**Issue by go-diego-go** [DataDog/dd-trace-py#796]
We're trying out the new logs injection feature but it doesn't seem to be working all the time. 
ERROR level logs do seem to be making it all the way but not INFO level logs. 
This same behavior is being reflected in the console (ERROR logs do show up but not INFO logs) so it seems like they're getting suppressed even before being sent. 

We're using `ddtrace-run` to integrate it, and some other things I've noticed include:
- If I turn on the `DATADOG_TRACE_DEBUG` flag, I'm able to see all the missing logs
- This is not a problem with our application per se because removing `ddtrace-run` makes the problem go away (i.e. logs start showing up in the console again)

This is our stack:
- ddtrace 0.19.0
- falcon 1.4.1
- gunicorn 19.9.0
- sqlalchemy 1.2.15
- structlog 18.2.0

We're using `structlog` for logs instead of directly using python's `logging` module

This is how we're setting that up:

```python
    import structlog
    import logging
    import sys

    logging.basicConfig(format='%(message)s', stream=sys.stdout, level=logging.DEBUG)

    RENDERER = structlog.processors.JSONRenderer()

    structlog.configure(
        processors=[
            structlog.stdlib.filter_by_level,
            structlog.stdlib.add_logger_name,
            structlog.stdlib.add_log_level,
            structlog.stdlib.PositionalArgumentsFormatter(),
            structlog.processors.TimeStamper(fmt='iso'),
            structlog.processors.StackInfoRenderer(),
            structlog.processors.format_exc_info,
            structlog.processors.UnicodeDecoder(),
            RENDERER,
        ],
        context_class=structlog.threadlocal.wrap_dict(dict),
        logger_factory=structlog.stdlib.LoggerFactory(),
        wrapper_class=structlog.stdlib.BoundLogger,
    )

```

and this is how we instantiate it:
```python
from structlog import get_logger

self.logger = get_logger('falcon-log').new()

```

I haven't yet tried to add the falcon middleware rather than using `ddtrace-run`, would that be a workaround? Or do they both eventually get to the same codebase?

Let me know if you need any more details

**Comment by go-diego-go** [comment]
Thanks @majorgreys !

Based on that insight I was able to get them working by calling `setLevel` on my structlog logger instance as you suggested. 
I'm able to see them both in the console and in Datadog now. 

I do see an issue with it nonetheless: My INFO logs are being categorized as ERRORs
Any ideas on how I could fix that?

The `level` and `logger` fields are also getting included as part of the message (at the beginning of it) and that didn't use to happen. 
It's not a deal breaker per se but it does seem a bit odd. 

Thanks!

**Comment by drytdubs** [comment]
@majorgreys I also ran into the log-swallowing issue, as our application code configures logging at startup using `basicConfig` and as you've called out, using `ddtrace-run` to wrap an application uses up the single use of basicConfig for the application.

The unexpected behavior from our perspective is that this call to `basicConfig` is triggered whether or not one intends to use log injection, setting the log level and formatting of the root logger.

```python
# DEV: Once basicConfig is called here, future calls to it cannot be used to
# change the formatter since it applies the formatter to the root handler only
# upon initializing it the first time.
# See https://github.com/python/cpython/blob/112e4afd582515fcdcc0cde5012a4866e5cfda12/Lib/logging/__init__.py#L1550
if debug and debug.lower() == 'true':
    logging.basicConfig(level=logging.DEBUG, format=DD_LOG_FORMAT)
else:
    logging.basicConfig(format=DD_LOG_FORMAT)
```

Since this is not unique to the use of log injection, it might be worth raising this comment out of the Advanced Usage section or re-factoring to allow application code to maintain ownership of the root logger config when not using log injection.

Thanks

**Comment by odannyc** [comment]
I'm also running into this same issue.
I configure the `logging.basicConfig` on my application side by adding level, formatters and handlers to it. Unfortunately `dd-trace` breaks my logging format.

**Comment by yesthesoup** [comment]
I had the same issue in my flask application. Application logs ended up being duplicated on DataDog because `dd-trace run` injected its configuration before I could configure it in the application. Instead of running my app with `dd-trace run`, I have

```
import ddtrace

ddtrace.patch_all()
```
before defining the Flask app.

[dd-trace-py's official documentation](http://pypi.datadoghq.com/trace/docs/web_integrations.html) was helpful and has more web framework examples.

**Comment by Kyle-Verhoog** [comment]
:wave: in `v0.50` we have [added a flag](https://github.com/DataDog/dd-trace-py/pull/2485/) `DD_CALL_BASIC_CONFIG` that can be used to prevent `ddtrace` from calling `basicConfig`. We realize this is a short term mitigation and long term we want to do away with calling `basicConfig` at all but cannot remove it due to backward compatibility for those who depend on it.

We are going to track this work with the following proposal: #2713

**Comment by mikejgray** [comment]
@go-diego-go Did you ever get a resolution to all of the logs being classified as errors in Datadog?
