### ISSUE TITLE
Module not installed error not informative enough

### ISSUE THREAD

**Issue by peter-featherstone** [DataDog/dd-trace-py#797]
It would be nice to see in the error output what modules are not installed when running the `patch()` method. We had a few modules explicitly patched this way but the error only told us `module not installed` meaning we had to try different combinations until we found the cause.

If we could have the module name explicitly in the error output it would be nice. I believe the change needs to be made on this line https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/monkey.py#L183 and changed to the below:

`raise PatchException('module not installed {}'.format(module))`

**Comment by majorgreys** [comment]
Thank you for pointing this out @peter-featherstone.

As of now, you should be seeing the module that is not patched when debugging is enabled (`DATADOG_TRACE_DEBUG=true`). 

The  `PatchException` is handled here:

https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/monkey.py#L152

Of course, turning on debugging in order to get the output you want is that the tracer would also be outputting the traces themselves. Can you tell us if this information in debug logs addresses your needs?

**Comment by brettlangdon** [comment]
@peter-featherstone are you still experiencing this issue?

Calling `ddtrace.patch()`, should be raising an exception, but `ddtrace.patch_all()` will swallow them and log instead.

**Comment by majorgreys** [comment]
We recently changed the logging of this information in #1506.

@peter-featherstone I'll close this issue due to inactivity but do re-open If your issue is still a problem.
