### ISSUE TITLE
Setup Tools Versioning: System Tests and setuptools_scm versioning

### ISSUE THREAD

**Issue by tabgok** [DataDog/dd-trace-py#8801]
### Summary of problem
See: https://github.com/DataDog/dd-trace-py/pull/8796 and its system tests for the failure.

System tests

tldr; the repo currently needs 'release-branch-semver' for main to get the next minor version for system tests and `guess-next-dev` for each release branch.  This involves a manual step to change the setuptools_scm version scheme whenever a release is done.  

From [christophe-papazian](https://github.com/christophe-papazian) in the PR:
```
We have 2 possible policies for setup tools, none of them is ok for all cases.
Setuptools is looking back from current commit and looking for the first version tag in ancestor commit.
Then either it’s using that version with release-branch-semver or using the next minor dev version with guess-next-dev

Currently we need the next minor dev version to be able to enable new system tests for new “just merged in main” features. But we need the same version policy for all backports, otherwise we will enable tests in system tests for features merged in the next version.

So for now, we are using 'release-branch-semver' in main and as soon as it’s needed we change it into “guess-next-dev” for minor version branches for all backports.

(This is a known problem that I already explained to a guild meeting, while sponsoring for one of the following solution, but this was never supported by the guild)

What are doing other big python projects on that problem ?

Do as we are doing (not really satisfying)
Use always “release-branch-semver” but add a new minor dev tag (for next unreleased minor version, like 4.15.0.dev) to the main branch on an empty commit after each creation of a new minor/major branch (like v4.14). We would need to integrate that step to our release todo list
Drop setuptools for version computation and have the version as constants in a file that would need to be updated for each release. Require more work but with less dependency, simpler build process and more control.
```

### How can we reproduce your problem?
N/A => see linked PR and system tests for how this is failing

**Comment by emmettbutler** [comment]
Here's exactly what happened to make this issue apparent:

[These tests](https://github.com/DataDog/system-tests/blob/81bc01790aa29d06d6f43f28ce01a34bc1b7ca94/tests/integrations/test_dsm.py#L340)  ran on [this pull request against 2.7](https://github.com/DataDog/dd-trace-py/pull/8771)  ([logs](https://github.com/DataDog/dd-trace-py/actions/runs/8438622702/job/23140963988)) despite the [system-tests manifest](https://github.com/DataDog/system-tests/blob/81bc01790aa29d06d6f43f28ce01a34bc1b7ca94/manifests/python.yml#L490) specifying that they should only run against versions of ddtracepy >=v2.8.0.dev. Ideally this test would not run on backport pull requests targeting release lines older than 2.8.0.dev.

**Comment by emmettbutler** [comment]
From my read of the [documentation](https://setuptools-scm.readthedocs.io/en/latest/extending/#available-implementations) for `release-branch-semver`, the setuptools_scm mode we use, the reason it's doing this is because the repo's release tags are prefixed with `v` but its release branches are not.

> The same as guess-next-dev (incrementing the pre-release or micro segment) however when on a release branch: a branch whose name (ignoring namespace) parses as a version that matches the most recent tag up to the minor segment. Otherwise if on a non-release branch, increments the minor segment and sets the micro segment to zero, then appends .devN

Translation:

> When on a release branch (a branch whose name parses as a version that matches the most recent tag up to the minor segment), does `guess-next-dev`. Otherwise, increments the minor segment and sets the micro segment to zero, then appends .devN.

Theory: `2.7` does not match `v2.7` (that is, "parse as a version that matches the most recent tag up to the minor segment")

**Comment by emmettbutler** [comment]
I don't think that theory is correct. New theory: because during pull request builds ddtrace is installed from a [detached HEAD state](https://github.com/DataDog/dd-trace-py/actions/runs/8438622702/job/23140963988#step:4:1595), there's no branch information for [release-branch-semver](https://github.com/pypa/setuptools_scm/blob/d081257ea39dfae710603796a9e85033256cc012/src/setuptools_scm/version.py#L280) to find, thus it [falls back](https://github.com/pypa/setuptools_scm/blob/d081257ea39dfae710603796a9e85033256cc012/src/setuptools_scm/version.py#L299) to the minor bump behavior that we've [observed](https://github.com/DataDog/dd-trace-py/actions/runs/8438622702/job/23140963988#step:5:226).
