### ISSUE TITLE
Django: Custom trace middleware support

### ISSUE THREAD

**Issue by kevinhyang** [DataDog/dd-trace-py#926]
We have a use case where we would like to extend TraceMiddleware and pick the service dynamically based on the request endpoint. The current structure seems rather rigid in the way the TraceMiddleware is inserted.

I was wondering if there are any current plans to extend this piece:
https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/django/apps.py#L41-L42
... to allow for more flexibility such as:
```
if settings.AUTO_INSERT_TRACE_MIDDLEWARE:
    insert_trace_middleware()
```
or
```
if settings.CUSTOM_TRACE_MIDDLEWARE:
...
```

If you guys feel that this is valuable in general, I could create a PR with this change. Let me know what you guys think.

cc: @rickhutcheson

**Comment by brettlangdon** [comment]
@kevinhyang could you explain your use case a little more in-depth? What are you trying to solve for? Is there a reason why you want to use a different service name based on the endpoint?

**Comment by kevinhyang** [comment]
Basically we're trying to use `RateByServiceSampler` to dynamically change the sample rate per request (ie. heavily used endpoints would get a sample rate of 0.1 whereas more lightly used important endpoints would get a sample rate of 1)

**Comment by kevinhyang** [comment]
@brettlangdon did you have any additional input?

A better way might be to allow `insert_trace_middleware` and `insert_exception_middleware` to pull `TRACE_MIDDLEWARE` and/or `EXCEPTION_MIDDLEWARE` from the settings instead of only allowing the default (hard coded) value here: https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/django/middleware.py#L54

Again, we're happy to do the work (just need a yay/nay from you guys). It would be clearer than us monkey patching this in our code.

**Comment by brettlangdon** [comment]
@kevinhyang sorry for the delay on my end.

I shared this feedback with the team internally to try and figure out if there is a better approach, but the only suggestion we have right now is to write your own sampler that inherits from our [AllSampler](https://github.com/DataDog/dd-trace-py/blob/f687bd38758cdbc30ef8c80e9c14e3badab20554/ddtrace/sampler.py#L18)

And then you can configure with:

```
from ddtrace import tracer

tracer.configure(sampler=CustomSampler(), priority_sampling=False)
```

This is a general approach you can take, but I am not 100% sure all the side effects from doing this since we generally don't recommend this approach, especially disabling priority sampling. But it might be an approach worth trying to find out if it solves your problem.

**Comment by kevinhyang** [comment]
@brettlangdon thanks for your response.

This won't work for us because:
1. The sampler does not have access to the request.
2. https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/tracer.py#L240 The root span gets set by `TraceMiddleware` (and TraceMiddleware gets inserted as the first middleware). Subsequent middlewares cannot adjust the sampler since the root span has already been started by TraceMiddleware.

**Comment by brettlangdon** [comment]
Closing this issue as we have a support thread tracking this.
