### ISSUE TITLE
tracer.current_span() not working like expected

### ISSUE THREAD

**Issue by SuyogSoti** [DataDog/dd-trace-py#968]
```python
from ddtrace import tracer as dd_tracer

client = MockClient(policies=[DistributedTracer()])
parent = dd_tracer.trace(name="Overall", service="suyog-azure-core-v0.01-datadog")
attrs = {"firstKey": "firstVal", "secondKey": "secondVal"}
client.make_request(2)
client.make_request(2, tracer="datadog")
client.make_request(2)
temp= dd_tracer.current_span()
print(temp.name)  # prints: make_request but we expect Overall
```

make_request creates and ends the span it creates. make_request also uses the dd_tracer.current_span() function. I would expect that the current span is the parent span which has the name "Overall". This may just be that I have the wrong idea on what to expect, but please advise.

**Comment by majorgreys** [comment]
@SuyogSoti, I am sorry it took us so long to follow up on your question.

Without seeing the contents of `make_request` it is hard for me to be sure where the problem is arising. But you are correct that `tracer.current_span()` should return the the "Overall" parent span if the child spans created by `make_request` have been finished. For instance:

```python
import ddtrace

def make_request(val):
    span = ddtrace.tracer.trace("make_request")
    print(">>>", ddtrace.tracer.current_span())
    span.set_tag("val", val)
    span.finish()

parent = ddtrace.tracer.trace("Overall", service="suyog-azure-core-v0.01-datadog")
print(ddtrace.tracer.current_span())
make_request(2)
print(ddtrace.tracer.current_span())
```

Outputs:

```
<Span(id=4126110913497512009,trace_id=17517243817165385114,parent_id=None,name=Overall)>
>>> <Span(id=8980451964924738320,trace_id=17517243817165385114,parent_id=4126110913497512009,name=make_request)>
<Span(id=4126110913497512009,trace_id=17517243817165385114,parent_id=None,name=Overall)>
```

Does this help? If not, can you please provide more complete reproducible code along with additional details on your Python interpreter, environment, and package versions?

**Comment by SuyogSoti** [comment]
Thank you so much. The problem has been resolved to my knowledge. Thanks!
